USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSV_MIXMGROUP]') AND type in (N'U'))
DROP TABLE [dbo].[CSV_MIXMGROUP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CSV_MIXMGROUP](
	[CMG_KCD] [int] NOT NULL,
	[CMG_TENCD] [int] NOT NULL,
	[CMG_HANEIYMD] [datetime] NULL,
	[CMG_TEKIYOYMD] [datetime] NOT NULL,
	[CMG_MMNO] [bigint] NOT NULL,
	[CMG_MMNAME] [varchar](60) NOT NULL,
	[CMG_MMSTR] [datetime] NOT NULL,
	[CMG_MMEND] [datetime] NOT NULL,
	[CMG_SETKOSU1] [int] NOT NULL,
	[CMG_SETKINGAKU1] [int] NOT NULL,
	[CMG_SETKOSU2] [int] NULL,
	[CMG_SETKINGAKU2] [int] NULL,
	[CMG_YDELKBN] [int] NOT NULL,
	[CMG_MDELKBN] [int] NOT NULL,
	[CMG_KOSINYMD] [datetime] NOT NULL,
	[CMG_YOBI1] [int] NULL,
	[CMG_YOBI2] [int] NULL,
	[CMG_YOBI3] [int] NULL,
	[CMG_YOBI4] [varchar](100) NULL,
	[CMG_YOBI5] [varchar](100) NULL,
	[CMG_YOBI6] [varchar](100) NULL,
	[CMG_YOBI7] [datetime] NULL,
	[CMG_YOBI8] [datetime] NULL,
	[CMG_YOBI9] [datetime] NULL,
	[CMG_IMPORTYMD] [datetime] NOT NULL,
	[CMG_IMPORTFILE] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CSV_MIXMGROUP] PRIMARY KEY CLUSTERED 
(
	[CMG_KCD] ASC,
	[CMG_TENCD] ASC,
	[CMG_TEKIYOYMD] ASC,
	[CMG_MMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
