USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSV_SHOSUPPORT]') AND type in (N'U'))
DROP TABLE [dbo].[CSV_SHOSUPPORT]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CSV_SHOSUPPORT](
	[CSS_KCD] [int] NOT NULL,
	[CSS_TENCD] [int] NOT NULL,
	[CSS_HANEIYMD] [datetime] NULL,
	[CSS_TEKIYOYMD] [datetime] NOT NULL,
	[CSS_KIKAKUCD] [bigint] NOT NULL,
	[CSS_KIKAKUKBN] [int] NULL,
	[CSS_SCD] [bigint] NOT NULL,
	[CSS_HAISTR] [datetime] NOT NULL,
	[CSS_HAIEND] [datetime] NOT NULL,
	[CSS_MAXBAIKA] [int] NULL,
	[CSS_100BAIKA] [int] NULL,
	[CSS_MINBAIKA] [int] NULL,
	[CSS_SURYOSEIGEN] [smallint] NULL,
	[CSS_SEIGYOKBN] [smallint] NULL,
	[CSS_TEISHIKBN] [smallint] NULL,
	[CSS_SJKBN] [int] NULL,
	[CSS_TYUKNRFLG] [tinyint] NULL,
	[CSS_MCHKKBN] [tinyint] NULL,
	[CSS_YDELKBN] [int] NOT NULL,
	[CSS_MDELKBN] [int] NOT NULL,
	[CSS_KOSINYMD] [datetime] NOT NULL,
	[CSS_YOBI1] [int] NULL,
	[CSS_YOBI2] [int] NULL,
	[CSS_YOBI3] [int] NULL,
	[CSS_YOBI4] [varchar](100) NULL,
	[CSS_YOBI5] [varchar](100) NULL,
	[CSS_YOBI6] [varchar](100) NULL,
	[CSS_YOBI7] [datetime] NULL,
	[CSS_YOBI8] [datetime] NULL,
	[CSS_YOBI9] [datetime] NULL,
	[CSS_IMPORTYMD] [datetime] NOT NULL,
	[CSS_IMPORTFILE] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CSV_SHOSUPPORT] PRIMARY KEY CLUSTERED 
(
	[CSS_KCD] ASC,
	[CSS_TENCD] ASC,
	[CSS_TEKIYOYMD] ASC,
	[CSS_SCD] ASC,
	[CSS_KIKAKUCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
