USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSV_CATSHOHIN]') AND type in (N'U'))
DROP TABLE [dbo].[CSV_CATSHOHIN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CSV_CATSHOHIN](
	[CCS_KCD] [int] NOT NULL,
	[CCS_CATSBT] [int] NOT NULL,
	[CCS_TENCD] [int] NOT NULL,
	[CCS_TEKIYOYMD] [datetime] NOT NULL,
	[CCS_LCATCD] [char](4) NOT NULL,
	[CCS_MCATCD] [char](4) NOT NULL,
	[CCS_SCATCD] [char](4) NOT NULL,
	[CCS_SCD] [bigint] NOT NULL,
	[CCS_APPKEISAIJYUN] [int] NOT NULL,
	[CCS_YDELKBN] [int] NOT NULL,
	[CCS_MDELKBN] [int] NOT NULL,
	[CCS_YOBI1] [int] NULL,
	[CCS_YOBI2] [int] NULL,
	[CCS_YOBI3] [int] NULL,
	[CCS_YOBI4] [varchar](100) NULL,
	[CCS_YOBI5] [varchar](100) NULL,
	[CCS_YOBI6] [varchar](100) NULL,
	[CCS_YOBI7] [datetime] NULL,
	[CCS_YOBI8] [datetime] NULL,
	[CCS_YOBI9] [datetime] NULL,
	[CCS_IMPORTYMD] [datetime] NOT NULL,
	[CCS_IMPORTFILE] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CSV_CATSHOHIN] PRIMARY KEY CLUSTERED 
(
	[CCS_KCD] ASC,
	[CCS_TENCD] ASC,
	[CCS_TEKIYOYMD] ASC,
	[CCS_LCATCD] ASC,
	[CCS_MCATCD] ASC,
	[CCS_SCATCD] ASC,
	[CCS_SCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
