USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSV_MIXMSHOHIN]') AND type in (N'U'))
DROP TABLE [dbo].[CSV_MIXMSHOHIN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CSV_MIXMSHOHIN](
	[CMS_KCD] [int] NOT NULL,
	[CMS_TENCD] [int] NOT NULL,
	[CMS_HANEIYMD] [datetime] NULL,
	[CMS_TEKIYOYMD] [datetime] NOT NULL,
	[CMS_MMNO] [bigint] NOT NULL,
	[CMS_SCD] [bigint] NOT NULL,
	[CMS_YDELKBN] [int] NOT NULL,
	[CMS_MDELKBN] [int] NOT NULL,
	[CMS_KOSINYMD] [datetime] NOT NULL,
	[CMS_YOBI1] [int] NULL,
	[CMS_YOBI2] [int] NULL,
	[CMS_YOBI3] [int] NULL,
	[CMS_YOBI4] [varchar](100) NULL,
	[CMS_YOBI5] [varchar](100) NULL,
	[CMS_YOBI6] [varchar](100) NULL,
	[CMS_YOBI7] [datetime] NULL,
	[CMS_YOBI8] [datetime] NULL,
	[CMS_YOBI9] [datetime] NULL,
	[CMS_IMPORTYMD] [datetime] NOT NULL,
	[CMS_IMPORTFILE] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CSV_MIXMSHOHIN] PRIMARY KEY CLUSTERED 
(
	[CMS_KCD] ASC,
	[CMS_TENCD] ASC,
	[CMS_TEKIYOYMD] ASC,
	[CMS_MMNO] ASC,
	[CMS_SCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
