USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_SHOHIN_MST]') AND type in (N'V'))
DROP VIEW [dbo].[vi_SHOHIN_MST]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_SHOHIN_MST]
AS
SELECT d.*, ISNULL(e.SSHM_TEKIYOYMD_END, CAST('9999/12/31 23:59:59' AS datetime)) AS SSHM_TEKIYOYMD_END
FROM (
	SELECT *
	FROM SHOHIN_MST_now
	WHERE SSHM_DELFG = 0) d
LEFT OUTER JOIN (
	SELECT c.SSHM_KCD, c.SSHM_HTCD, c.SSHM_SCD, c.SSHM_TEKIYOYMD, DATEADD(second, -1, MIN(c.SSHM_TEKIYOYMD_END)) AS SSHM_TEKIYOYMD_END
	FROM (
		SELECT a.SSHM_KCD, a.SSHM_HTCD, a.SSHM_SCD, a.SSHM_TEKIYOYMD, b.SSHM_TEKIYOYMD AS SSHM_TEKIYOYMD_END
		FROM (
			SELECT *
			FROM SHOHIN_MST_now
			WHERE SSHM_DELFG <> 1) a
		INNER JOIN (
			SELECT *
			FROM SHOHIN_MST_now
			WHERE SSHM_DELFG <> 1) b
		ON a.SSHM_KCD = b.SSHM_KCD
			AND a.SSHM_HTCD = b.SSHM_HTCD
			AND a.SSHM_SCD = b.SSHM_SCD
			AND a.SSHM_TEKIYOYMD < b.SSHM_TEKIYOYMD) c
	GROUP BY c.SSHM_KCD, c.SSHM_HTCD, c.SSHM_SCD, c.SSHM_TEKIYOYMD) e
ON d.SSHM_KCD = e.SSHM_KCD
	AND d.SSHM_HTCD = e.SSHM_HTCD
	AND d.SSHM_SCD = e.SSHM_SCD
	AND d.SSHM_TEKIYOYMD = e.SSHM_TEKIYOYMD

GO
