USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SHOHIN_MST_SET_1]') AND type in (N'P'))
DROP PROCEDURE [dbo].[SHOHIN_MST_SET_1]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- ====================================================
-- 名称			: SHOHIN_MST_SET_1
-- 機能			: テーブル SHOHIN_MST のレコード 1 件を登録する。
--					: SSHM_DELFG = 2 の場合は、適用日以降を無設定とし、他のマスタも同様に無設定とする。
-- 引き数		: 
-- 戻り値		: 
-- 作成日		: 2022/03/03  作成者 : 茅川
-- ====================================================
CREATE PROCEDURE [dbo].[SHOHIN_MST_SET_1]
	@SSHM_KCD int,
	@SSHM_HTCD int,
	@SSHM_SCD bigint,
	@SSHM_TEKIYOYMD datetime,
	@SSHM_UPDATECNT int,
	@SSHM_JANCD1 varchar(20),
	@SSHM_JANCD2 varchar(20),
	@SSHM_JANCD3 varchar(20),
	@SSHM_JANCD4 varchar(20),
	@SSHM_JANCD5 varchar(20),
	@SSHM_JANINYMD1 datetime,
	@SSHM_JANINYMD2 datetime,
	@SSHM_JANINYMD3 datetime,
	@SSHM_JANINYMD4 datetime,
	@SSHM_JANINYMD5 datetime,
	@SSHM_GAIHANSCD varchar(20),
	@SSHM_BUMONCD smallint,
	@SSHM_BURUICD int,
	@SSHM_SHONAME nvarchar(100),
	@SSHM_MAKNAME varchar(30),
	@SSHM_HINNAME varchar(60),
	@SSHM_KIKNAME1 varchar(60),
	@SSHM_KIKNAME2 varchar(20),
	@SSHM_SURYOSEIGEN smallint,
	@SSHM_STANKA float,
	@SSHM_STANKAHON float,
	@SSHM_TANKA int,
	@SSHM_YOUKIKBN tinyint,
	@SSHM_JUNOUKIKAN tinyint,
	@SSHM_JUCHUSTR datetime,
	@SSHM_JUCHUEND datetime,
	@SSHM_HAISTR datetime,
	@SSHM_HAIEND datetime,
	@SSHM_HAITEISTR datetime,
	@SSHM_HAITEIEND datetime,
	@SSHM_KEISAIPAGE smallint,
	@SSHM_KEISAIJUN int,
	@SSHM_YOUBIKBN varchar(7),
	@SSHM_TOKUSHOKBN tinyint,
	@SSHM_BUNKATU tinyint,
	@SSHM_TANAGON smallint,
	@SSHM_TANADAN tinyint,
	@SSHM_TANANARA tinyint,
	@SSHM_TANAFACE tinyint,
	@SSHM_TANAADDRESS varchar(8),
	@SSHM_URIZEIKBN tinyint,
	@SSHM_SIIREZEIKBN tinyint,
	@SSHM_ZEIRITUKBN tinyint,
	@SSHM_SIIRECD int,
	@SSHM_FSKIKAKUNO int,
	@SSHM_HTORIKBN tinyint,
	@SSHM_PICKKBN tinyint,
	@SSHM_SFILENAME varchar(30),
	@SSHM_KEISAIFLG tinyint,
	@SSHM_FAVBTNDFLG tinyint,
	@SSHM_TYUKNRFLG tinyint,
	@SSHM_SJKBN int,
	@SSHM_SEBANGO varchar(20),
	@SSHM_NEWSORTKEY int,
	@SSHM_SIMETIME datetime,
	@SSHM_DISPCONTROLFLG bit,
	@SSHM_COMMENTDISPFLG bit,
	@SSHM_KISETUKBN tinyint,
	@SSHM_OYASCD varchar(20),
	@SSHM_FUTEIKANKBN tinyint,
	@SSHM_NAIYO varchar(1000),
	@SSHM_GENZAIRYO varchar(1000),
	@SSHM_SEIBUN varchar(1000),
	@SSHM_KEYWORD varchar(200),
	@SSHM_CHIRASHIKBN tinyint,
	@SSHM_JUCYUKOSINFLG tinyint,
	@SSHM_JANCD6 varchar(20),
	@SSHM_JANCD7 varchar(20),
	@SSHM_JANCD8 varchar(20),
	@SSHM_JANCD9 varchar(20),
	@SSHM_SURYOSEIGEN_M smallint,
	@SSHM_SEIGYOKBN smallint,
	@SSHM_TEISHIKBN smallint,
	@SSHM_RANK tinyint,
	@SSHM_MYSHNKBN tinyint,
	@SSHM_TOBASHIDISPKBN tinyint,
	@SSHM_NOTSEARCHKBN tinyint,
	@SSHM_KENSACD int,
	@SSHM_100BAIKA int,
	@SSHM_MAXBAIKA int,
	@SSHM_MINBAIKA int,
	@SSHM_MAXGRAM int,
	@SSHM_MINGRAM int,
	@SSHM_ALLERGEN varchar(500),
	@SSHM_YDELKBN int,
	@SSHM_MDELKBN int,
	@SSHM_YOBI1 int,
	@SSHM_YOBI2 int,
	@SSHM_YOBI3 int,
	@SSHM_YOBI4 varchar(100),
	@SSHM_YOBI5 varchar(100),
	@SSHM_YOBI6 varchar(100),
	@SSHM_YOBI7 datetime,
	@SSHM_YOBI8 datetime,
	@SSHM_YOBI9 datetime,
	@SSHM_IMPORTYMD datetime,
	@SSHM_IMPORTFILE varchar(100),
	@SSHM_DELFG tinyint,
	@SSHM_INYMD datetime,
	@SSHM_INTANTO varchar(100),
	@SSHM_KOSINYMD datetime,
	@SSHM_KOSINTANTO varchar(100)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ErrMessage nvarchar(4000), @ErrSeverity int, @ErrState int;
	DECLARE @TranCnt int;

	BEGIN TRY
		SET @TranCnt = @@TRANCOUNT;

		IF @TranCnt > 0
			SAVE TRANSACTION svpt_SHOHIN_MST_SET_1_1;
		ELSE 
			BEGIN TRANSACTION;
	END TRY
	BEGIN CATCH
		SET @ErrMessage = ERROR_MESSAGE();
        SET @ErrSeverity = ERROR_SEVERITY();
        SET @ErrState = ERROR_STATE();
  
        RAISERROR (@ErrMessage, @ErrSeverity, @ErrState);
	END CATCH

	BEGIN TRY
		INSERT INTO SHOHIN_MST_now
		VALUES (
			@SSHM_KCD,
			@SSHM_HTCD,
			@SSHM_SCD,
			@SSHM_TEKIYOYMD,
			@SSHM_UPDATECNT,
			@SSHM_JANCD1,
			@SSHM_JANCD2,
			@SSHM_JANCD3,
			@SSHM_JANCD4,
			@SSHM_JANCD5,
			@SSHM_JANINYMD1,
			@SSHM_JANINYMD2,
			@SSHM_JANINYMD3,
			@SSHM_JANINYMD4,
			@SSHM_JANINYMD5,
			@SSHM_GAIHANSCD,
			@SSHM_BUMONCD,
			@SSHM_BURUICD,
			@SSHM_SHONAME,
			@SSHM_MAKNAME,
			@SSHM_HINNAME,
			@SSHM_KIKNAME1,
			@SSHM_KIKNAME2,
			@SSHM_SURYOSEIGEN,
			@SSHM_STANKA,
			@SSHM_STANKAHON,
			@SSHM_TANKA,
			@SSHM_YOUKIKBN,
			@SSHM_JUNOUKIKAN,
			@SSHM_JUCHUSTR,
			@SSHM_JUCHUEND,
			@SSHM_HAISTR,
			@SSHM_HAIEND,
			@SSHM_HAITEISTR,
			@SSHM_HAITEIEND,
			@SSHM_KEISAIPAGE,
			@SSHM_KEISAIJUN,
			@SSHM_YOUBIKBN,
			@SSHM_TOKUSHOKBN,
			@SSHM_BUNKATU,
			@SSHM_TANAGON,
			@SSHM_TANADAN,
			@SSHM_TANANARA,
			@SSHM_TANAFACE,
			@SSHM_TANAADDRESS,
			@SSHM_URIZEIKBN,
			@SSHM_SIIREZEIKBN,
			@SSHM_ZEIRITUKBN,
			@SSHM_SIIRECD,
			@SSHM_FSKIKAKUNO,
			@SSHM_HTORIKBN,
			@SSHM_PICKKBN,
			@SSHM_SFILENAME,
			@SSHM_KEISAIFLG,
			@SSHM_FAVBTNDFLG,
			@SSHM_TYUKNRFLG,
			@SSHM_SJKBN,
			@SSHM_SEBANGO,
			@SSHM_NEWSORTKEY,
			@SSHM_SIMETIME,
			@SSHM_DISPCONTROLFLG,
			@SSHM_COMMENTDISPFLG,
			@SSHM_KISETUKBN,
			@SSHM_OYASCD,
			@SSHM_FUTEIKANKBN,
			@SSHM_NAIYO,
			@SSHM_GENZAIRYO,
			@SSHM_SEIBUN,
			@SSHM_KEYWORD,
			@SSHM_CHIRASHIKBN,
			@SSHM_JUCYUKOSINFLG,
			@SSHM_JANCD6,
			@SSHM_JANCD7,
			@SSHM_JANCD8,
			@SSHM_JANCD9,
			@SSHM_SURYOSEIGEN_M,
			@SSHM_SEIGYOKBN,
			@SSHM_TEISHIKBN,
			@SSHM_RANK,
			@SSHM_MYSHNKBN,
			@SSHM_TOBASHIDISPKBN,
			@SSHM_NOTSEARCHKBN,
			@SSHM_KENSACD,
			@SSHM_100BAIKA,
			@SSHM_MAXBAIKA,
			@SSHM_MINBAIKA,
			@SSHM_MAXGRAM,
			@SSHM_MINGRAM,
			@SSHM_ALLERGEN,
			@SSHM_YDELKBN,
			@SSHM_MDELKBN,
			@SSHM_YOBI1,
			@SSHM_YOBI2,
			@SSHM_YOBI3,
			@SSHM_YOBI4,
			@SSHM_YOBI5,
			@SSHM_YOBI6,
			@SSHM_YOBI7,
			@SSHM_YOBI8,
			@SSHM_YOBI9,
			@SSHM_IMPORTYMD,
			@SSHM_IMPORTFILE,
			@SSHM_DELFG,
			@SSHM_INYMD,
			@SSHM_INTANTO,
			@SSHM_KOSINYMD,
			@SSHM_KOSINTANTO
		);

		IF @SSHM_DELFG <> 2
		BEGIN
			IF @TranCnt = 0
				COMMIT TRANSACTION;

			RETURN;
		END;

		DECLARE @now datetime = GETDATE();

		-- SHOHIN_MST

		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_1
		FROM SHOHIN_MST_now
		WHERE SSHM_KCD = @SSHM_KCD
			AND SSHM_HTCD = @SSHM_HTCD
			AND SSHM_SCD = @SSHM_SCD
			AND SSHM_TEKIYOYMD > @SSHM_TEKIYOYMD
			AND SSHM_DELFG <> 1;

		UPDATE #wt_SHOHIN_MST_SET_1_1
		SET SSHM_DELFG = 1,
			SSHM_KOSINYMD = @now,
			SSHM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1';

		INSERT INTO SHOHIN_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_1;

		DROP TABLE #wt_SHOHIN_MST_SET_1_1;

		-- APP_CATSHN_MST
		
		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_11
		FROM ft_APP_CATSHN_MST(@SSHM_TEKIYOYMD)
		WHERE SCSM_KCD = @SSHM_KCD
			AND SCSM_HTCD = @SSHM_HTCD
			AND SCSM_SCD = @SSHM_SCD;

		UPDATE #wt_SHOHIN_MST_SET_1_11
		SET SCSM_TEKIYOYMD = @SSHM_TEKIYOYMD,
			SCSM_UPDATECNT = 0,
			SCSM_DELFG = 2,
			SCSM_INYMD = @now,
			SCSM_INTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1',
			SCSM_KOSINYMD = @now,
			SCSM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE SCSM_TEKIYOYMD < @SSHM_TEKIYOYMD;

		UPDATE #wt_SHOHIN_MST_SET_1_11
		SET SCSM_DELFG = 2,
			SCSM_KOSINYMD = @now,
			SCSM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE SCSM_TEKIYOYMD = @SSHM_TEKIYOYMD;

		INSERT INTO APP_CATSHN_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_11;

		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_12
		FROM APP_CATSHN_MST_now
		WHERE SCSM_KCD = @SSHM_KCD
			AND SCSM_HTCD = @SSHM_HTCD
			AND SCSM_SCD = @SSHM_SCD
			AND SCSM_TEKIYOYMD > @SSHM_TEKIYOYMD
			AND SCSM_DELFG <> 1;

		UPDATE #wt_SHOHIN_MST_SET_1_12
		SET SCSM_DELFG = 1,
			SCSM_KOSINYMD = @now,
			SCSM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1';

		INSERT INTO APP_CATSHN_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_12;

		DROP TABLE #wt_SHOHIN_MST_SET_1_11;
		DROP TABLE #wt_SHOHIN_MST_SET_1_12;

		-- KAKAKU_MST
		
		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_21
		FROM ft_KAKAKU_MST(@SSHM_TEKIYOYMD)
		WHERE SKAK_KCD = @SSHM_KCD
			AND SKAK_HTCD = @SSHM_HTCD
			AND SKAK_SCD = @SSHM_SCD;

		UPDATE #wt_SHOHIN_MST_SET_1_21
		SET SKAK_TEKIYOYMD = @SSHM_TEKIYOYMD,
			SKAK_UPDATECNT = 0,
			SKAK_DELFG = 2,
			SKAK_INYMD = @now,
			SKAK_INTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1',
			SKAK_KOSINYMD = @now,
			SKAK_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE SKAK_TEKIYOYMD < @SSHM_TEKIYOYMD;

		UPDATE #wt_SHOHIN_MST_SET_1_21
		SET SKAK_DELFG = 2,
			SKAK_KOSINYMD = @now,
			SKAK_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE SKAK_TEKIYOYMD = @SSHM_TEKIYOYMD;

		INSERT INTO KAKAKU_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_21;

		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_22
		FROM KAKAKU_MST_now
		WHERE SKAK_KCD = @SSHM_KCD
			AND SKAK_HTCD = @SSHM_HTCD
			AND SKAK_SCD = @SSHM_SCD
			AND SKAK_TEKIYOYMD > @SSHM_TEKIYOYMD
			AND SKAK_DELFG <> 1;

		UPDATE #wt_SHOHIN_MST_SET_1_22
		SET SKAK_DELFG = 1,
			SKAK_KOSINYMD = @now,
			SKAK_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1';

		INSERT INTO KAKAKU_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_22;

		DROP TABLE #wt_SHOHIN_MST_SET_1_21;
		DROP TABLE #wt_SHOHIN_MST_SET_1_22;

		-- MIXMATCH_MST
		
		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_31
		FROM ft_MIXMATCH_MST(@SSHM_TEKIYOYMD)
		WHERE SMIM_KCD = @SSHM_KCD
			AND SMIM_HTCD = @SSHM_HTCD
			AND SMIM_SCD = @SSHM_SCD;

		UPDATE #wt_SHOHIN_MST_SET_1_31
		SET SMIM_TEKIYOYMD = @SSHM_TEKIYOYMD,
			SMIM_UPDATECNT = 0,
			SMIM_DELFG = 2,
			SMIM_INYMD = @now,
			SMIM_INTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1',
			SMIM_KOSINYMD = @now,
			SMIM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE SMIM_TEKIYOYMD < @SSHM_TEKIYOYMD;

		UPDATE #wt_SHOHIN_MST_SET_1_31
		SET SMIM_DELFG = 2,
			SMIM_KOSINYMD = @now,
			SMIM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE SMIM_TEKIYOYMD = @SSHM_TEKIYOYMD;

		INSERT INTO MIXMATCH_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_31;

		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_32
		FROM MIXMATCH_MST_now
		WHERE SMIM_KCD = @SSHM_KCD
			AND SMIM_HTCD = @SSHM_HTCD
			AND SMIM_SCD = @SSHM_SCD
			AND SMIM_TEKIYOYMD > @SSHM_TEKIYOYMD
			AND SMIM_DELFG <> 1;

		UPDATE #wt_SHOHIN_MST_SET_1_32
		SET SMIM_DELFG = 1,
			SMIM_KOSINYMD = @now,
			SMIM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1';

		INSERT INTO MIXMATCH_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_32;

		---- MIXMATCHGRP_MST（商品が削除されたので、定期ジョブで受注ＤＢへの再登録が試みられるよう、レコードを更新しておく。商品数が 0 なら、グループは受注ＤＢに登録されない。）
		SELECT a.*
		INTO #wt_SHOHIN_MST_SET_1_33
		FROM ft_MIXMATCHGRP_MST(@SSHM_TEKIYOYMD) a
		INNER JOIN #wt_SHOHIN_MST_SET_1_31 b
		ON a.SMGM_KCD = b.SMIM_KCD
			AND a.SMGM_HTCD = b.SMIM_HTCD
			AND a.SMGM_MMNO = b.SMIM_MMNO;

		UPDATE #wt_SHOHIN_MST_SET_1_33
		SET SMGM_KOSINYMD = @now,
			SMGM_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1';

		INSERT INTO MIXMATCHGRP_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_33;

		DROP TABLE #wt_SHOHIN_MST_SET_1_31;
		DROP TABLE #wt_SHOHIN_MST_SET_1_32;
		DROP TABLE #wt_SHOHIN_MST_SET_1_33;

		-- TYUMON_KNR_MST
		
		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_41
		FROM ft_TYUMON_KNR_MST(@SSHM_TEKIYOYMD)
		WHERE STKF_KCD = @SSHM_KCD
			AND STKF_HTCD = @SSHM_HTCD
			AND STKF_SCD = @SSHM_SCD;

		UPDATE #wt_SHOHIN_MST_SET_1_41
		SET STKF_TEKIYOYMD = @SSHM_TEKIYOYMD,
			STKF_UPDATECNT = 0,
			STKF_DELFG = 2,
			STKF_INYMD = @now,
			STKF_INTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1',
			STKF_KOSINYMD = @now,
			STKF_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE STKF_TEKIYOYMD < @SSHM_TEKIYOYMD;

		UPDATE #wt_SHOHIN_MST_SET_1_41
		SET STKF_DELFG = 2,
			STKF_KOSINYMD = @now,
			STKF_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1'
		WHERE STKF_TEKIYOYMD = @SSHM_TEKIYOYMD;

		INSERT INTO TYUMON_KNR_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_41;

		SELECT *
		INTO #wt_SHOHIN_MST_SET_1_42
		FROM TYUMON_KNR_MST_now
		WHERE STKF_KCD = @SSHM_KCD
			AND STKF_HTCD = @SSHM_HTCD
			AND STKF_SCD = @SSHM_SCD
			AND STKF_TEKIYOYMD > @SSHM_TEKIYOYMD
			AND STKF_DELFG <> 1;

		UPDATE #wt_SHOHIN_MST_SET_1_42
		SET STKF_DELFG = 1,
			STKF_KOSINYMD = @now,
			STKF_KOSINTANTO = 'sqlserv_proc_SHOHIN_MST_SET_1';

		INSERT INTO TYUMON_KNR_MST_now
		SELECT *
		FROM #wt_SHOHIN_MST_SET_1_42;

		DROP TABLE #wt_SHOHIN_MST_SET_1_41;
		DROP TABLE #wt_SHOHIN_MST_SET_1_42;

		IF @TranCnt = 0
            COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @TranCnt = 0  
            ROLLBACK TRANSACTION;
		ELSE IF XACT_STATE() <> -1
			ROLLBACK TRANSACTION svpt_SHOHIN_MST_SET_1_1;

		SET @ErrMessage = ERROR_MESSAGE();
        SET @ErrSeverity = ERROR_SEVERITY();
        SET @ErrState = ERROR_STATE();
  
        RAISERROR (@ErrMessage, @ErrSeverity, @ErrState );
	END CATCH
END
GO
