USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APP_CATSHN_MST_now]') AND type in (N'U'))
DROP TABLE [dbo].[APP_CATSHN_MST_now]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_CATSHN_MST_now](
	[SCSM_KCD] [int] NOT NULL,
	[SCSM_HTCD] [int] NOT NULL,
	[SCSM_LCATCD] [char](4) NOT NULL,
	[SCSM_MCATCD] [char](4) NOT NULL,
	[SCSM_SCATCD] [char](4) NOT NULL,
	[SCSM_SCD] [bigint] NOT NULL,
	[SCSM_TEKIYOYMD] [datetime] NOT NULL,
	[SCSM_UPDATECNT] [int] NOT NULL,
	[SCSM_CATSBT] [int] NOT NULL,
	[SCSM_APPKEISAIJYUN] [int] NOT NULL,
	[SCSM_YDELKBN] [int] NOT NULL,
	[SCSM_MDELKBN] [int] NOT NULL,
	[SCSM_YOBI1] [int] NULL,
	[SCSM_YOBI2] [int] NULL,
	[SCSM_YOBI3] [int] NULL,
	[SCSM_YOBI4] [varchar](100) NULL,
	[SCSM_YOBI5] [varchar](100) NULL,
	[SCSM_YOBI6] [varchar](100) NULL,
	[SCSM_YOBI7] [datetime] NULL,
	[SCSM_YOBI8] [datetime] NULL,
	[SCSM_YOBI9] [datetime] NULL,
	[SCSM_IMPORTYMD] [datetime] NOT NULL,
	[SCSM_IMPORTFILE] [varchar](100) NOT NULL,
	[SCSM_DELFG] [tinyint] NOT NULL,
	[SCSM_INYMD] [datetime] NOT NULL,
	[SCSM_INTANTO] [varchar](100) NOT NULL,
	[SCSM_KOSINYMD] [datetime] NOT NULL,
	[SCSM_KOSINTANTO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_APP_CATSHN_MST_now] PRIMARY KEY CLUSTERED 
(
	[SCSM_KCD] ASC,
	[SCSM_HTCD] ASC,
	[SCSM_LCATCD] ASC,
	[SCSM_MCATCD] ASC,
	[SCSM_SCATCD] ASC,
	[SCSM_SCD] ASC,
	[SCSM_TEKIYOYMD] ASC,
	[SCSM_UPDATECNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
