USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_APP_CATSHN_MST]') AND type in (N'V'))
DROP VIEW [dbo].[vi_APP_CATSHN_MST]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_APP_CATSHN_MST]
AS
SELECT d.*, ISNULL(e.SCSM_TEKIYOYMD_END, CAST('9999/12/31 23:59:59' AS datetime)) AS SCSM_TEKIYOYMD_END
FROM (
	SELECT *
	FROM APP_CATSHN_MST_now
	WHERE SCSM_DELFG = 0) d
LEFT OUTER JOIN (
	SELECT c.SCSM_KCD, c.SCSM_HTCD, c.SCSM_LCATCD, c.SCSM_MCATCD, c.SCSM_SCATCD, c.SCSM_SCD, c.SCSM_TEKIYOYMD, DATEADD(second, -1, MIN(c.SCSM_TEKIYOYMD_END)) AS SCSM_TEKIYOYMD_END
	FROM (
		SELECT a.SCSM_KCD, a.SCSM_HTCD, a.SCSM_LCATCD, a.SCSM_MCATCD, a.SCSM_SCATCD, a.SCSM_SCD, a.SCSM_TEKIYOYMD, b.SCSM_TEKIYOYMD AS SCSM_TEKIYOYMD_END
		FROM (
			SELECT *
			FROM APP_CATSHN_MST_now
			WHERE SCSM_DELFG <> 1) a
		INNER JOIN (
			SELECT *
			FROM APP_CATSHN_MST_now
			WHERE SCSM_DELFG <> 1) b
		ON a.SCSM_KCD = b.SCSM_KCD
			AND a.SCSM_HTCD = b.SCSM_HTCD
			AND a.SCSM_LCATCD = b.SCSM_LCATCD
			AND a.SCSM_MCATCD = b.SCSM_MCATCD
			AND a.SCSM_SCATCD = b.SCSM_SCATCD
			AND a.SCSM_SCD = b.SCSM_SCD
			AND a.SCSM_TEKIYOYMD < b.SCSM_TEKIYOYMD) c
	GROUP BY c.SCSM_KCD, c.SCSM_HTCD, c.SCSM_LCATCD, c.SCSM_MCATCD, c.SCSM_SCATCD, c.SCSM_SCD, c.SCSM_TEKIYOYMD) e
ON d.SCSM_KCD = e.SCSM_KCD
	AND d.SCSM_HTCD = e.SCSM_HTCD
	AND d.SCSM_LCATCD = e.SCSM_LCATCD
	AND d.SCSM_MCATCD = e.SCSM_MCATCD
	AND d.SCSM_SCATCD = e.SCSM_SCATCD
	AND d.SCSM_SCD = e.SCSM_SCD
	AND d.SCSM_TEKIYOYMD = e.SCSM_TEKIYOYMD

GO
