USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_MIXMATCH_MST]') AND type in (N'V'))
DROP VIEW [dbo].[vi_MIXMATCH_MST]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_MIXMATCH_MST]
AS
SELECT d.*, ISNULL(e.SMIM_TEKIYOYMD_END, CAST('9999/12/31 23:59:59' AS datetime)) AS SMIM_TEKIYOYMD_END
FROM (
	SELECT *
	FROM MIXMATCH_MST_now
	WHERE SMIM_DELFG = 0) d
LEFT OUTER JOIN (
	SELECT c.SMIM_KCD, c.SMIM_HTCD, c.SMIM_MMNO, c.SMIM_SCD, c.SMIM_TEKIYOYMD, DATEADD(second, -1, MIN(c.SMIM_TEKIYOYMD_END)) AS SMIM_TEKIYOYMD_END
	FROM (
		SELECT a.SMIM_KCD, a.SMIM_HTCD, a.SMIM_MMNO, a.SMIM_SCD, a.SMIM_TEKIYOYMD, b.SMIM_TEKIYOYMD AS SMIM_TEKIYOYMD_END
		FROM (
			SELECT *
			FROM MIXMATCH_MST_now
			WHERE SMIM_DELFG <> 1) a
		INNER JOIN (
			SELECT *
			FROM MIXMATCH_MST_now
			WHERE SMIM_DELFG <> 1) b
		ON a.SMIM_KCD = b.SMIM_KCD
			AND a.SMIM_HTCD = b.SMIM_HTCD
			AND a.SMIM_MMNO = b.SMIM_MMNO
			AND a.SMIM_SCD = b.SMIM_SCD
			AND a.SMIM_TEKIYOYMD < b.SMIM_TEKIYOYMD) c
	GROUP BY c.SMIM_KCD, c.SMIM_HTCD, c.SMIM_MMNO, c.SMIM_SCD, c.SMIM_TEKIYOYMD) e
ON d.SMIM_KCD = e.SMIM_KCD
	AND d.SMIM_HTCD = e.SMIM_HTCD
	AND d.SMIM_MMNO = e.SMIM_MMNO
	AND d.SMIM_SCD = e.SMIM_SCD
	AND d.SMIM_TEKIYOYMD = e.SMIM_TEKIYOYMD

GO
