USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MIXMATCH_MST_now]') AND type in (N'U'))
DROP TABLE [dbo].[MIXMATCH_MST_now]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MIXMATCH_MST_now](
	[SMIM_KCD] [int] NOT NULL,
	[SMIM_HTCD] [int] NOT NULL,
	[SMIM_MMNO] [int] NOT NULL,
	[SMIM_SCD] [bigint] NOT NULL,
	[SMIM_TEKIYOYMD] [datetime] NOT NULL,
	[SMIM_UPDATECNT] [int] NOT NULL,
	[SMIM_HANEIYMD] [datetime] NULL,
	[SMIM_MMNOBIG] [bigint] NULL,
	[SMIM_YDELKBN] [int] NOT NULL,
	[SMIM_MDELKBN] [int] NOT NULL,
	[SMIM_YOBI1] [int] NULL,
	[SMIM_YOBI2] [int] NULL,
	[SMIM_YOBI3] [int] NULL,
	[SMIM_YOBI4] [varchar](100) NULL,
	[SMIM_YOBI5] [varchar](100) NULL,
	[SMIM_YOBI6] [varchar](100) NULL,
	[SMIM_YOBI7] [datetime] NULL,
	[SMIM_YOBI8] [datetime] NULL,
	[SMIM_YOBI9] [datetime] NULL,
	[SMIM_IMPORTYMD] [datetime] NOT NULL,
	[SMIM_IMPORTFILE] [varchar](100) NOT NULL,
	[SMIM_DELFG] [tinyint] NOT NULL,
	[SMIM_INYMD] [datetime] NOT NULL,
	[SMIM_INTANTO] [varchar](100) NOT NULL,
	[SMIM_KOSINYMD] [datetime] NOT NULL,
	[SMIM_KOSINTANTO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_MIXMATCH_MST_now] PRIMARY KEY CLUSTERED 
(
	[SMIM_KCD] ASC,
	[SMIM_HTCD] ASC,
	[SMIM_MMNO] ASC,
	[SMIM_SCD] ASC,
	[SMIM_TEKIYOYMD] ASC,
	[SMIM_UPDATECNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
