USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MIXMATCHGRP_MST_now]') AND type in (N'U'))
DROP TABLE [dbo].[MIXMATCHGRP_MST_now]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MIXMATCHGRP_MST_now](
	[SMGM_KCD] [int] NOT NULL,
	[SMGM_HTCD] [int] NOT NULL,
	[SMGM_MMNO] [int] NOT NULL,
	[SMGM_TEKIYOYMD] [datetime] NOT NULL,
	[SMGM_UPDATECNT] [int] NOT NULL,
	[SMGM_HANEIYMD] [datetime] NULL,
	[SMGM_MMNOBIG] [bigint] NULL,
	[SMGM_MMNAME] [varchar](60) NOT NULL,
	[SMGM_MMSTR] [datetime] NOT NULL,
	[SMGM_MMEND] [datetime] NOT NULL,
	[SMGM_SETKOSU1] [int] NOT NULL,
	[SMGM_SETKINGAKU1] [int] NOT NULL,
	[SMGM_SETKOSU2] [int] NULL,
	[SMGM_SETKINGAKU2] [int] NULL,
	[SMGM_YDELKBN] [int] NOT NULL,
	[SMGM_MDELKBN] [int] NOT NULL,
	[SMGM_YOBI1] [int] NULL,
	[SMGM_YOBI2] [int] NULL,
	[SMGM_YOBI3] [int] NULL,
	[SMGM_YOBI4] [varchar](100) NULL,
	[SMGM_YOBI5] [varchar](100) NULL,
	[SMGM_YOBI6] [varchar](100) NULL,
	[SMGM_YOBI7] [datetime] NULL,
	[SMGM_YOBI8] [datetime] NULL,
	[SMGM_YOBI9] [datetime] NULL,
	[SMGM_IMPORTYMD] [datetime] NOT NULL,
	[SMGM_IMPORTFILE] [varchar](100) NOT NULL,
	[SMGM_DELFG] [tinyint] NOT NULL,
	[SMGM_INYMD] [datetime] NOT NULL,
	[SMGM_INTANTO] [varchar](100) NOT NULL,
	[SMGM_KOSINYMD] [datetime] NOT NULL,
	[SMGM_KOSINTANTO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_MIXMATCHGRP_MST_now] PRIMARY KEY CLUSTERED 
(
	[SMGM_KCD] ASC,
	[SMGM_HTCD] ASC,
	[SMGM_MMNO] ASC,
	[SMGM_TEKIYOYMD] ASC,
	[SMGM_UPDATECNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
