USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_TYUMON_KNR_MST]') AND type in (N'V'))
DROP VIEW [dbo].[vi_TYUMON_KNR_MST]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_TYUMON_KNR_MST]
AS
SELECT d.*, ISNULL(e.STKF_TEKIYOYMD_END, CAST('9999/12/31 23:59:59' AS datetime)) AS STKF_TEKIYOYMD_END
FROM (
	SELECT *
	FROM TYUMON_KNR_MST_now
	WHERE STKF_DELFG = 0) d
LEFT OUTER JOIN (
	SELECT c.STKF_KCD, c.STKF_HTCD, c.STKF_SCD, c.STKF_STR, c.STKF_END, c.STKF_TEKIYOYMD, DATEADD(second, -1, MIN(c.STKF_TEKIYOYMD_END)) AS STKF_TEKIYOYMD_END
	FROM (
		SELECT a.STKF_KCD, a.STKF_HTCD, a.STKF_SCD, a.STKF_STR, a.STKF_END, a.STKF_TEKIYOYMD, b.STKF_TEKIYOYMD AS STKF_TEKIYOYMD_END
		FROM (
			SELECT *
			FROM TYUMON_KNR_MST_now
			WHERE STKF_DELFG <> 1) a
		INNER JOIN (
			SELECT *
			FROM TYUMON_KNR_MST_now
			WHERE STKF_DELFG <> 1) b
		ON a.STKF_KCD = b.STKF_KCD
			AND a.STKF_HTCD = b.STKF_HTCD
			AND a.STKF_SCD = b.STKF_SCD
			AND a.STKF_STR = b.STKF_STR
			AND a.STKF_END = b.STKF_END
			AND a.STKF_TEKIYOYMD < b.STKF_TEKIYOYMD) c
	GROUP BY c.STKF_KCD, c.STKF_HTCD, c.STKF_SCD, c.STKF_STR, c.STKF_END, c.STKF_TEKIYOYMD) e
ON d.STKF_KCD = e.STKF_KCD
	AND d.STKF_HTCD = e.STKF_HTCD
	AND d.STKF_SCD = e.STKF_SCD
	AND d.STKF_STR = e.STKF_STR
	AND d.STKF_END = e.STKF_END
	AND d.STKF_TEKIYOYMD = e.STKF_TEKIYOYMD

GO
