USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TENPO_SETNO_MST_now]') AND type in (N'U'))
DROP TABLE [dbo].[TENPO_SETNO_MST_now]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TENPO_SETNO_MST_now](
	[TSM_KCD_1] [int] NOT NULL,
	[TSM_TENSETNO] [int] NOT NULL,
	[TSM_KCD_2] [int] NOT NULL,
	[TSM_TENCD] [int] NOT NULL,
	[TSM_TEKIYOYMD] [datetime] NOT NULL,
	[TSM_UPDATECNT] [int] NOT NULL,
	[TSM_DELFG] [tinyint] NOT NULL,
	[TSM_INYMD] [datetime] NOT NULL,
	[TSM_INTANTO] [varchar](100) NOT NULL,
	[TSM_KOSINYMD] [datetime] NOT NULL,
	[TSM_KOSINTANTO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TENPO_SETNO_MST_now] PRIMARY KEY CLUSTERED 
(
	[TSM_KCD_1] ASC,
	[TSM_TENSETNO] ASC,
	[TSM_KCD_2] ASC,
	[TSM_TENCD] ASC,
	[TSM_TEKIYOYMD] ASC,
	[TSM_UPDATECNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
