USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOG_IMPORT]') AND type in (N'U'))
DROP TABLE [dbo].[LOG_IMPORT]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOG_IMPORT](
	[LI_FILENAME] [nvarchar](100) NOT NULL,
	[LI_LOGYMD] [datetime] NOT NULL,
	[LI_FILETYPE] [nvarchar](50) NOT NULL,
	[LI_CNT_CSVLINE] [int] NULL,
	[LI_CNT_DBUPDATE] [int] NOT NULL,
 CONSTRAINT [PK_LOG_IMPORT] PRIMARY KEY CLUSTERED 
(
	[LI_FILENAME] ASC,
	[LI_LOGYMD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
