USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SID_SCD_PAIR_USED]') AND type in (N'U'))
DROP TABLE [dbo].[SID_SCD_PAIR_USED]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SID_SCD_PAIR_USED](
	[SSP_SID] [varchar](20) NOT NULL,
	[SSP_SCD] [bigint] NOT NULL,
	[SSP_INYMD] [datetime] NOT NULL,
 CONSTRAINT [PK_SID_SCD_PAIR_USED] PRIMARY KEY CLUSTERED 
(
	[SSP_SCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
