USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MIXMATCH_MMNO]') AND type in (N'U'))
DROP TABLE [dbo].[MIXMATCH_MMNO]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MIXMATCH_MMNO](
	[CSVMMNO] [bigint] NULL,
	[MMNO] [int] NOT NULL,
	[ENDYMD] [datetime] NULL,
 CONSTRAINT [PK_MIXMATCH_MMNO] PRIMARY KEY CLUSTERED 
(
	[MMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

WITH
	t1 AS (
	  SELECT 0 AS num	-- 開始値
	  UNION ALL
	  SELECT num + 1
	  FROM t1
	  WHERE t1.num < 9	-- 最終値
	),
	t2 AS (
		SELECT 1 AS num
		FROM t1 a
		CROSS JOIN t1 b
		CROSS JOIN t1 c
	),
	t3 AS (
		SELECT ROW_NUMBER() OVER (ORDER BY num) AS num
		FROM t2
	)
INSERT INTO MIXMATCH_MMNO
SELECT
	NULL,
	num,
	NULL
FROM t3
WHERE num < 1000
GO
