USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[IMPORT_SHOSUPPORT]') AND type in (N'P'))
DROP PROCEDURE [dbo].[IMPORT_SHOSUPPORT]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- ====================================================
-- 名称			: IMPORT_SHOSUPPORT
-- 機能			: テーブル KAKAKU_MST_now に CSV データを取り込む。
-- 引き数		: 
-- 戻り値		: 
-- 作成日		: 2021/05/04  作成者 : 茅川
-- 更新日		: 2021/11/08　茅川
-- ====================================================
CREATE PROCEDURE [dbo].[IMPORT_SHOSUPPORT]
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ErrMessage nvarchar(4000), @ErrSeverity int, @ErrState int;
	DECLARE @TranCnt int;

	BEGIN TRY
		SET @TranCnt = @@TRANCOUNT;

		IF @TranCnt > 0
			SAVE TRANSACTION svpt_IMPORT_SHOSUPPORT_1;
		ELSE 
			BEGIN TRANSACTION;
	END TRY
	BEGIN CATCH
		SET @ErrMessage = ERROR_MESSAGE();
        SET @ErrSeverity = ERROR_SEVERITY();
        SET @ErrState = ERROR_STATE();
  
        RAISERROR (@ErrMessage, @ErrSeverity, @ErrState);
	END CATCH

	BEGIN TRY
		DECLARE @NowDt datetime = GETDATE();
		DECLARE @Tanto varchar(100) = 'sqlserv_proc_IMPORT_SHOSUPPORT';

		DECLARE @SJKBN varchar(40);
		SELECT @SJKBN = [SSTM_SETVALUE_VC]
		FROM [dbo].[SETTING_MST] WITH(NOLOCK)
		WHERE [SSTM_KCD] = 9999 AND [SSTM_SETKBN] = 'KakakuM_Override' AND [SSTM_SETDTLKBN] = 'X';

		IF @SJKBN IS NULL
		BEGIN
			SET @ErrMessage = N'テーブル [SETTING_MST] に "KakakuM_Override" の設定が見つかりません。';
			SET @ErrSeverity = 11;
			SET @ErrState = 1;

			RAISERROR (@ErrMessage, @ErrSeverity, @ErrState);
		END;

-- [会社コード、店舗コード、商品コード、適用日、企画コード] で予約削除
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_TEKIYOYMD, CSS_KIKAKUCD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_1
				WHERE CSS_YDELKBN = 1
			),
			t2 AS (
				SELECT SKAK_KCD, SKAK_HTCD, SKAK_SCD, SKAK_TEKIYOYMD, SKAK_KIKAKUCD
				FROM KAKAKU_MST_now
				WHERE SKAK_DELFG <> 1
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD, t1.CSS_KIKAKUCD, t1.CSS_IMPORTFILE, t2.SKAK_KCD AS CSS_KCD_2
		INTO #wt_IMPORT_SHOSUPPORT_2
		FROM t1
		LEFT OUTER JOIN t2
		ON t1.CSS_KCD = t2.SKAK_KCD
			AND t1.CSS_TENCD = t2.SKAK_HTCD
			AND t1.CSS_SCD = t2.SKAK_SCD
			AND t1.CSS_TEKIYOYMD = t2.SKAK_TEKIYOYMD
			AND t1.CSS_KIKAKUCD = t2.SKAK_KIKAKUCD;

  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_TEKIYOYMD, CSS_KIKAKUCD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_2
				WHERE CSS_KCD_2 IS NULL
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD, t1.CSS_KIKAKUCD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CSS_IMPORTFILE, LEN(t1.CSS_IMPORTFILE) - PATINDEX('%|%', t1.CSS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CSS_KCD = t2.SSHM_KCD
			AND t1.CSS_TENCD = t2.SSHM_HTCD
			AND t1.CSS_SCD = t2.SSHM_SCD
			AND t1.CSS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CSS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t1 AS (
				SELECT *
				FROM KAKAKU_MST_now
				WHERE SKAK_DELFG <> 1
			)
		SELECT t1.*
		INTO #wt_IMPORT_SHOSUPPORT_3
		FROM t1
		INNER JOIN #wt_IMPORT_SHOSUPPORT_2 t2
		ON t1.SKAK_KCD = t2.CSS_KCD
			AND t1.SKAK_HTCD = t2.CSS_TENCD
			AND t1.SKAK_SCD = t2.CSS_SCD
			AND t1.SKAK_TEKIYOYMD = t2.CSS_TEKIYOYMD
			AND t1.SKAK_KIKAKUCD = t2.CSS_KIKAKUCD;

  -- 削除対象レコードの [削除フラグ] を設定
		UPDATE #wt_IMPORT_SHOSUPPORT_3
		SET
			SKAK_DELFG = 1,
			SKAK_KOSINYMD = @NowDt,
			SKAK_KOSINTANTO = @Tanto;
			
  -- ＤＢレコードを更新
		INSERT INTO KAKAKU_MST_now
		SELECT *
		FROM #wt_IMPORT_SHOSUPPORT_3;
		
-- [会社コード、店舗コード、商品コード] で予約削除（※ [適用日] 以降）
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_TEKIYOYMD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_1
				WHERE CSS_YDELKBN = 2
			),
			t2 AS (
				SELECT SKAK_KCD, SKAK_HTCD, SKAK_SCD, SKAK_TEKIYOYMD
				FROM KAKAKU_MST_now
				WHERE SKAK_DELFG <> 1
			),
			t3 AS (
				SELECT DISTINCT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD
				FROM t1
				INNER JOIN t2
				ON t1.CSS_KCD = t2.SKAK_KCD
					AND t1.CSS_TENCD = t2.SKAK_HTCD
					AND t1.CSS_SCD = t2.SKAK_SCD
					AND t1.CSS_TEKIYOYMD <= t2.SKAK_TEKIYOYMD
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD, t1.CSS_IMPORTFILE, t3.CSS_KCD AS CSS_KCD_2
		INTO #wt_IMPORT_SHOSUPPORT_4
		FROM t1
		LEFT OUTER JOIN t3
		ON t1.CSS_KCD = t3.CSS_KCD
			AND t1.CSS_TENCD = t3.CSS_TENCD
			AND t1.CSS_SCD = t3.CSS_SCD
			AND t1.CSS_TEKIYOYMD = t3.CSS_TEKIYOYMD;
			
  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_TEKIYOYMD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_4
				WHERE CSS_KCD_2 IS NULL
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CSS_IMPORTFILE, LEN(t1.CSS_IMPORTFILE) - PATINDEX('%|%', t1.CSS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CSS_KCD = t2.SSHM_KCD
			AND t1.CSS_TENCD = t2.SSHM_HTCD
			AND t1.CSS_SCD = t2.SSHM_SCD
			AND t1.CSS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CSS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t1 AS (
				SELECT *
				FROM KAKAKU_MST_now
				WHERE SKAK_DELFG <> 1
			),
			t2 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, MIN(CSS_TEKIYOYMD) AS CSS_TEKIYOYMD
				FROM #wt_IMPORT_SHOSUPPORT_4
				WHERE CSS_KCD_2 IS NOT NULL
				GROUP BY CSS_KCD, CSS_TENCD, CSS_SCD
			)
		SELECT t1.*
		INTO #wt_IMPORT_SHOSUPPORT_5
		FROM t1
		INNER JOIN t2
		ON t1.SKAK_KCD = t2.CSS_KCD
			AND t1.SKAK_HTCD = t2.CSS_TENCD
			AND t1.SKAK_SCD = t2.CSS_SCD
			AND t1.SKAK_TEKIYOYMD >= t2.CSS_TEKIYOYMD;
			
  -- 削除対象レコードの [削除フラグ] を設定
		UPDATE #wt_IMPORT_SHOSUPPORT_5
		SET
			SKAK_DELFG = 1,
			SKAK_KOSINYMD = @NowDt,
			SKAK_KOSINTANTO = @Tanto;
			
  -- ＤＢレコードを更新
		INSERT INTO KAKAKU_MST_now
		SELECT *
		FROM #wt_IMPORT_SHOSUPPORT_5;
		
-- [会社コード、店舗コード、商品コード、企画コード] でマスタ削除（※ [適用日] 時点）
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_KIKAKUCD, CSS_TEKIYOYMD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_1
				WHERE CSS_MDELKBN = 1
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_KIKAKUCD, t1.CSS_TEKIYOYMD, t1.CSS_IMPORTFILE, t2.SKAK_TEKIYOYMD
		INTO #wt_IMPORT_SHOSUPPORT_101
		FROM t1
		LEFT OUTER JOIN vi_KAKAKU_MST t2
		ON t1.CSS_KCD = t2.SKAK_KCD
			AND t1.CSS_TENCD = t2.SKAK_HTCD
			AND t1.CSS_SCD = t2.SKAK_SCD
			AND t1.CSS_KIKAKUCD = t2.SKAK_KIKAKUCD
			AND t1.CSS_TEKIYOYMD >= t2.SKAK_TEKIYOYMD
			AND t1.CSS_TEKIYOYMD <= t2.SKAK_TEKIYOYMD_END;

  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_KIKAKUCD, CSS_TEKIYOYMD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_101
				WHERE SKAK_TEKIYOYMD IS NULL
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_KIKAKUCD, t1.CSS_TEKIYOYMD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CSS_IMPORTFILE, LEN(t1.CSS_IMPORTFILE) - PATINDEX('%|%', t1.CSS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CSS_KCD = t2.SSHM_KCD
			AND t1.CSS_TENCD = t2.SSHM_HTCD
			AND t1.CSS_SCD = t2.SSHM_SCD
			AND t1.CSS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CSS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t1 AS (
				SELECT *
				FROM KAKAKU_MST_now
				WHERE SKAK_DELFG = 0
			)
		SELECT t1.*, t2.CSS_TEKIYOYMD
		INTO #wt_IMPORT_SHOSUPPORT_102
		FROM t1
		INNER JOIN #wt_IMPORT_SHOSUPPORT_101 t2
		ON t1.SKAK_KCD = t2.CSS_KCD
			AND t1.SKAK_HTCD = t2.CSS_TENCD
			AND t1.SKAK_SCD = t2.CSS_SCD
			AND t1.SKAK_KIKAKUCD = t2.CSS_KIKAKUCD
			AND t1.SKAK_TEKIYOYMD = t2.SKAK_TEKIYOYMD;

  -- 削除対象レコードを編集
		UPDATE #wt_IMPORT_SHOSUPPORT_102
		SET
			SKAK_TEKIYOYMD = CSS_TEKIYOYMD,
			SKAK_UPDATECNT = 0,
			SKAK_DELFG = 2,
			SKAK_INYMD = @NowDt,
			SKAK_INTANTO = @Tanto,
			SKAK_KOSINYMD = @NowDt,
			SKAK_KOSINTANTO = @Tanto
		WHERE SKAK_TEKIYOYMD < CSS_TEKIYOYMD;

		UPDATE #wt_IMPORT_SHOSUPPORT_102
		SET
			SKAK_DELFG = 2,
			SKAK_KOSINYMD = @NowDt,
			SKAK_KOSINTANTO = @Tanto
		WHERE SKAK_TEKIYOYMD = CSS_TEKIYOYMD;
			
  -- ＤＢレコードを更新
		INSERT INTO KAKAKU_MST_now
		SELECT SKAK_KCD,
			SKAK_HTCD,
			SKAK_SCD,
			SKAK_TOKUSTR,
			SKAK_TOKUEND,
			SKAK_TEKIYOYMD,
			SKAK_UPDATECNT,
			SKAK_HANEIYMD,
			SKAK_KIKAKUCD,
			SKAK_KIKAKUKBN,
			SKAK_TOKUKBN,
			SKAK_TOKUGENKA,
			SKAK_TOKUTANKA,
			SKAK_TSURYOSEIGEN,
			SKAK_TOKUKEISAIJUN,
			SKAK_MAXBAIKA,
			SKAK_100BAIKA,
			SKAK_MINBAIKA,
			SKAK_SURYOSEIGEN,
			SKAK_SEIGYOKBN,
			SKAK_TEISHIKBN,
			SKAK_TOKUSJKBN,
			SKAK_TYUKNRFLG,
			SKAK_MCHKKBN,
			SKAK_YDELKBN,
			SKAK_MDELKBN,
			SKAK_YOBI1,
			SKAK_YOBI2,
			SKAK_YOBI3,
			SKAK_YOBI4,
			SKAK_YOBI5,
			SKAK_YOBI6,
			SKAK_YOBI7,
			SKAK_YOBI8,
			SKAK_YOBI9,
			SKAK_IMPORTYMD,
			SKAK_IMPORTFILE,
			SKAK_KEISAI_OVERRIDE,
			SKAK_DELFG,
			SKAK_INYMD,
			SKAK_INTANTO,
			SKAK_KOSINYMD,
			SKAK_KOSINTANTO
		FROM #wt_IMPORT_SHOSUPPORT_102;

-- [会社コード、店舗コード、商品コード] でマスタ削除（※ [適用日] 時点）
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_TEKIYOYMD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_1
				WHERE CSS_MDELKBN = 2
			),
			t2 AS (
				SELECT DISTINCT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD
				FROM t1
				INNER JOIN vi_KAKAKU_MST t2
				ON t1.CSS_KCD = t2.SKAK_KCD
					AND t1.CSS_TENCD = t2.SKAK_HTCD
					AND t1.CSS_SCD = t2.SKAK_SCD
					AND t1.CSS_TEKIYOYMD >= t2.SKAK_TEKIYOYMD
					AND t1.CSS_TEKIYOYMD <= t2.SKAK_TEKIYOYMD_END
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD, t1.CSS_IMPORTFILE, t2.CSS_KCD AS CSS_KCD_2
		INTO #wt_IMPORT_SHOSUPPORT_103
		FROM t1
		LEFT OUTER JOIN t2
		ON t1.CSS_KCD = t2.CSS_KCD
			AND t1.CSS_TENCD = t2.CSS_TENCD
			AND t1.CSS_SCD = t2.CSS_SCD
			AND t1.CSS_TEKIYOYMD = t2.CSS_TEKIYOYMD;

  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_TEKIYOYMD, CSS_IMPORTFILE
				FROM #wt_IMPORT_SHOSUPPORT_103
				WHERE CSS_KCD_2 IS NULL
			)
		SELECT t1.CSS_KCD, t1.CSS_TENCD, t1.CSS_SCD, t1.CSS_TEKIYOYMD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CSS_IMPORTFILE, LEN(t1.CSS_IMPORTFILE) - PATINDEX('%|%', t1.CSS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CSS_KCD = t2.SSHM_KCD
			AND t1.CSS_TENCD = t2.SSHM_HTCD
			AND t1.CSS_SCD = t2.SSHM_SCD
			AND t1.CSS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CSS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t2 AS (
				SELECT DISTINCT CSS_KCD, CSS_TENCD, CSS_SCD, CSS_TEKIYOYMD
				FROM #wt_IMPORT_SHOSUPPORT_103
			)
		SELECT t1.*, t2.CSS_TEKIYOYMD
		INTO #wt_IMPORT_SHOSUPPORT_104
		FROM vi_KAKAKU_MST t1
		INNER JOIN t2
		ON t1.SKAK_KCD = t2.CSS_KCD
			AND t1.SKAK_HTCD = t2.CSS_TENCD
			AND t1.SKAK_SCD = t2.CSS_SCD
			AND t1.SKAK_TEKIYOYMD <= t2.CSS_TEKIYOYMD
			AND t1.SKAK_TEKIYOYMD_END >= t2.CSS_TEKIYOYMD;

  -- 削除対象レコードを編集
		UPDATE #wt_IMPORT_SHOSUPPORT_104
		SET
			SKAK_TEKIYOYMD = CSS_TEKIYOYMD,
			SKAK_UPDATECNT = 0,
			SKAK_DELFG = 2,
			SKAK_INYMD = @NowDt,
			SKAK_INTANTO = @Tanto,
			SKAK_KOSINYMD = @NowDt,
			SKAK_KOSINTANTO = @Tanto
		WHERE SKAK_TEKIYOYMD < CSS_TEKIYOYMD;

		UPDATE #wt_IMPORT_SHOSUPPORT_104
		SET
			SKAK_DELFG = 2,
			SKAK_KOSINYMD = @NowDt,
			SKAK_KOSINTANTO = @Tanto
		WHERE SKAK_TEKIYOYMD = CSS_TEKIYOYMD;
			
  -- ＤＢレコードを更新
		INSERT INTO KAKAKU_MST_now
		SELECT SKAK_KCD,
			SKAK_HTCD,
			SKAK_SCD,
			SKAK_TOKUSTR,
			SKAK_TOKUEND,
			SKAK_TEKIYOYMD,
			SKAK_UPDATECNT,
			SKAK_HANEIYMD,
			SKAK_KIKAKUCD,
			SKAK_KIKAKUKBN,
			SKAK_TOKUKBN,
			SKAK_TOKUGENKA,
			SKAK_TOKUTANKA,
			SKAK_TSURYOSEIGEN,
			SKAK_TOKUKEISAIJUN,
			SKAK_MAXBAIKA,
			SKAK_100BAIKA,
			SKAK_MINBAIKA,
			SKAK_SURYOSEIGEN,
			SKAK_SEIGYOKBN,
			SKAK_TEISHIKBN,
			SKAK_TOKUSJKBN,
			SKAK_TYUKNRFLG,
			SKAK_MCHKKBN,
			SKAK_YDELKBN,
			SKAK_MDELKBN,
			SKAK_YOBI1,
			SKAK_YOBI2,
			SKAK_YOBI3,
			SKAK_YOBI4,
			SKAK_YOBI5,
			SKAK_YOBI6,
			SKAK_YOBI7,
			SKAK_YOBI8,
			SKAK_YOBI9,
			SKAK_IMPORTYMD,
			SKAK_IMPORTFILE,
			SKAK_KEISAI_OVERRIDE,
			SKAK_DELFG,
			SKAK_INYMD,
			SKAK_INTANTO,
			SKAK_KOSINYMD,
			SKAK_KOSINTANTO
		FROM #wt_IMPORT_SHOSUPPORT_104;

-- レコード登録
		SELECT t1.*, t2.*,
			(CASE WHEN t3.CD IS NULL THEN 0 ELSE 1 END) AS KEISAI_OVERRIDE
		INTO #wt_IMPORT_SHOSUPPORT_6
		FROM #wt_IMPORT_SHOSUPPORT_1 t1
		LEFT OUTER JOIN KAKAKU_MST_now t2
		ON t1.CSS_KCD = t2.SKAK_KCD
			AND t1.CSS_TENCD = t2.SKAK_HTCD
			AND t1.CSS_SCD = t2.SKAK_SCD
			AND t1.CSS_TEKIYOYMD = t2.SKAK_TEKIYOYMD
			AND t1.CSS_KIKAKUCD = t2.SKAK_KIKAKUCD
		LEFT OUTER JOIN [dbo].[GET_CODELIST](@SJKBN) t3
		ON t1.CSS_SJKBN = t3.CD;

  -- レコード更新
    -- 予約・マスタ 削除レコード
		INSERT INTO KAKAKU_MST_now
		SELECT
			SKAK_KCD,
			SKAK_HTCD,
			SKAK_SCD,
			SKAK_TOKUSTR,
			SKAK_TOKUEND,
			SKAK_TEKIYOYMD,
			SKAK_UPDATECNT,
			SKAK_HANEIYMD,
			SKAK_KIKAKUCD,
			SKAK_KIKAKUKBN,
			SKAK_TOKUKBN,
			SKAK_TOKUGENKA,
			SKAK_MAXBAIKA,
			SKAK_SURYOSEIGEN,
			SKAK_TOKUKEISAIJUN,
			SKAK_MAXBAIKA,
			SKAK_100BAIKA,
			SKAK_MINBAIKA,
			SKAK_SURYOSEIGEN,
			SKAK_SEIGYOKBN,
			SKAK_TEISHIKBN,
			SKAK_TOKUSJKBN,
			SKAK_TYUKNRFLG,
			SKAK_MCHKKBN,
			CSS_YDELKBN,
			CSS_MDELKBN,
			SKAK_YOBI1,
			SKAK_YOBI2,
			SKAK_YOBI3,
			SKAK_YOBI4,
			SKAK_YOBI5,
			SKAK_YOBI6,
			SKAK_YOBI7,
			SKAK_YOBI8,
			SKAK_YOBI9,
			CSS_IMPORTYMD,
			CSS_IMPORTFILE,
			SKAK_KEISAI_OVERRIDE,
			SKAK_DELFG,
			SKAK_INYMD,
			SKAK_INTANTO,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_SHOSUPPORT_6
		WHERE SKAK_KCD IS NOT NULL
			AND CSS_YDELKBN + CSS_MDELKBN > 0;

    -- 通常レコード
		INSERT INTO KAKAKU_MST_now
		SELECT
			SKAK_KCD,
			SKAK_HTCD,
			SKAK_SCD,
			SKAK_TOKUSTR,
			SKAK_TOKUEND,
			SKAK_TEKIYOYMD,
			SKAK_UPDATECNT,
			CSS_HANEIYMD,
			CSS_KIKAKUCD,
			CSS_KIKAKUKBN,
			SKAK_TOKUKBN,
			SKAK_TOKUGENKA,
			ISNULL(CSS_MAXBAIKA, 0),
			ISNULL(CSS_SURYOSEIGEN, 0),
			SKAK_TOKUKEISAIJUN,
			CSS_MAXBAIKA,
			CSS_100BAIKA,
			CSS_MINBAIKA,
			ISNULL(CSS_SURYOSEIGEN, 0),
			CSS_SEIGYOKBN,
			CSS_TEISHIKBN,
			ISNULL(CSS_SJKBN, 0),
			CSS_TYUKNRFLG,
			CSS_MCHKKBN,
			CSS_YDELKBN,
			CSS_MDELKBN,
			CSS_YOBI1,
			CSS_YOBI2,
			CSS_YOBI3,
			CSS_YOBI4,
			CSS_YOBI5,
			CSS_YOBI6,
			CSS_YOBI7,
			CSS_YOBI8,
			CSS_YOBI9,
			CSS_IMPORTYMD,
			CSS_IMPORTFILE,
			KEISAI_OVERRIDE,
			0,
			SKAK_INYMD,
			SKAK_INTANTO,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_SHOSUPPORT_6
		WHERE SKAK_KCD IS NOT NULL
			AND CSS_YDELKBN = 0 AND CSS_MDELKBN = 0;

  -- レコード追加
    -- 予約・マスタ 削除レコード
		INSERT INTO KAKAKU_MST_now
		SELECT
			CSS_KCD,
			CSS_TENCD,
			CSS_SCD,
			CSS_HAISTR,
			CSS_HAIEND,
			CSS_TEKIYOYMD,
			0,
			CSS_HANEIYMD,
			CSS_KIKAKUCD,
			CSS_KIKAKUKBN,
			0,
			0,
			ISNULL(CSS_MAXBAIKA, 0),
			ISNULL(CSS_SURYOSEIGEN, 0),
			0,
			CSS_MAXBAIKA,
			CSS_100BAIKA,
			CSS_MINBAIKA,
			ISNULL(CSS_SURYOSEIGEN, 0),
			CSS_SEIGYOKBN,
			CSS_TEISHIKBN,
			ISNULL(CSS_SJKBN, 0),
			CSS_TYUKNRFLG,
			CSS_MCHKKBN,
			CSS_YDELKBN,
			CSS_MDELKBN,
			CSS_YOBI1,
			CSS_YOBI2,
			CSS_YOBI3,
			CSS_YOBI4,
			CSS_YOBI5,
			CSS_YOBI6,
			CSS_YOBI7,
			CSS_YOBI8,
			CSS_YOBI9,
			CSS_IMPORTYMD,
			CSS_IMPORTFILE,
			KEISAI_OVERRIDE,
			1,
			@NowDt,
			@Tanto,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_SHOSUPPORT_6
		WHERE SKAK_KCD IS NULL
			AND CSS_YDELKBN + CSS_MDELKBN > 0;

    -- 通常レコード
		INSERT INTO KAKAKU_MST_now
		SELECT
			CSS_KCD,
			CSS_TENCD,
			CSS_SCD,
			CSS_HAISTR,
			CSS_HAIEND,
			CSS_TEKIYOYMD,
			0,
			CSS_HANEIYMD,
			CSS_KIKAKUCD,
			CSS_KIKAKUKBN,
			0,
			0,
			ISNULL(CSS_MAXBAIKA, 0),
			ISNULL(CSS_SURYOSEIGEN, 0),
			0,
			CSS_MAXBAIKA,
			CSS_100BAIKA,
			CSS_MINBAIKA,
			ISNULL(CSS_SURYOSEIGEN, 0),
			CSS_SEIGYOKBN,
			CSS_TEISHIKBN,
			ISNULL(CSS_SJKBN, 0),
			CSS_TYUKNRFLG,
			CSS_MCHKKBN,
			CSS_YDELKBN,
			CSS_MDELKBN,
			CSS_YOBI1,
			CSS_YOBI2,
			CSS_YOBI3,
			CSS_YOBI4,
			CSS_YOBI5,
			CSS_YOBI6,
			CSS_YOBI7,
			CSS_YOBI8,
			CSS_YOBI9,
			CSS_IMPORTYMD,
			CSS_IMPORTFILE,
			KEISAI_OVERRIDE,
			0,
			@NowDt,
			@Tanto,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_SHOSUPPORT_6
		WHERE SKAK_KCD IS NULL
			AND CSS_YDELKBN = 0 AND CSS_MDELKBN = 0;

		IF @TranCnt = 0
            COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @TranCnt = 0  
            ROLLBACK TRANSACTION;
		ELSE IF XACT_STATE() <> -1
			ROLLBACK TRANSACTION svpt_IMPORT_SHOSUPPORT_1;

		SET @ErrMessage = ERROR_MESSAGE();
        SET @ErrSeverity = ERROR_SEVERITY();
        SET @ErrState = ERROR_STATE();
  
        RAISERROR (@ErrMessage, @ErrSeverity, @ErrState );
	END CATCH
END
GO
