USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[IMPORT_CATSHOHIN]') AND type in (N'P'))
DROP PROCEDURE [dbo].[IMPORT_CATSHOHIN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- ====================================================
-- 名称			: IMPORT_CATSHOHIN
-- 機能			: テーブル APP_CATSHN_MST_now に CSV データを取り込む。
-- 引き数		: 
-- 戻り値		: 
-- 作成日		: 2021/06/18  作成者 : 茅川
-- ====================================================
CREATE PROCEDURE [dbo].[IMPORT_CATSHOHIN]
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ErrMessage nvarchar(4000), @ErrSeverity int, @ErrState int;
	DECLARE @TranCnt int;

	BEGIN TRY
		SET @TranCnt = @@TRANCOUNT;

		IF @TranCnt > 0
			SAVE TRANSACTION svpt_IMPORT_CATSHOHIN_1;
		ELSE 
			BEGIN TRANSACTION;
	END TRY
	BEGIN CATCH
		SET @ErrMessage = ERROR_MESSAGE();
        SET @ErrSeverity = ERROR_SEVERITY();
        SET @ErrState = ERROR_STATE();
  
        RAISERROR (@ErrMessage, @ErrSeverity, @ErrState);
	END CATCH

	BEGIN TRY
		-- mandai 固有（掲載順補正）
		WITH
			t1 AS (
				SELECT AOR_SCD, MAX(AOR_GPCD) AS MAX_GPCD
				FROM R020_APP_ORDER_TRN
				GROUP BY AOR_SCD
			),
			t2 AS (
				SELECT a.*
				FROM R020_APP_ORDER_TRN a
				INNER JOIN t1
				ON a.AOR_SCD = t1.AOR_SCD
					AND a.AOR_GPCD = t1.MAX_GPCD
			)
		UPDATE a
		SET CCS_APPKEISAIJYUN = t2.AOR_APPKEISAIJYUN
		FROM #wt_IMPORT_CATSHOHIN_1 a
		INNER JOIN t2
		ON a.CCS_SCD = t2.AOR_SCD;

		DECLARE @NowDt datetime = GETDATE();
		DECLARE @Tanto varchar(100) = 'sqlserv_proc_IMPORT_CATSHOHIN';

-- [会社コード、店舗コード、商品コード、適用日、大カテゴリコード、中カテゴリコード、小カテゴリコード] で予約削除
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_TEKIYOYMD, CCS_LCATCD, CCS_MCATCD, CCS_SCATCD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_1
				WHERE CCS_YDELKBN = 1
			),
			t2 AS (
				SELECT SCSM_KCD, SCSM_HTCD, SCSM_SCD, SCSM_TEKIYOYMD, SCSM_LCATCD, SCSM_MCATCD, SCSM_SCATCD
				FROM APP_CATSHN_MST_now
				WHERE SCSM_DELFG <> 1
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_TEKIYOYMD, t1.CCS_LCATCD, t1.CCS_MCATCD, t1.CCS_SCATCD, t1.CCS_IMPORTFILE, t2.SCSM_KCD AS CCS_KCD_2
		INTO #wt_IMPORT_CATSHOHIN_2
		FROM t1
		LEFT OUTER JOIN t2
		ON t1.CCS_KCD = t2.SCSM_KCD
			AND t1.CCS_TENCD = t2.SCSM_HTCD
			AND t1.CCS_SCD = t2.SCSM_SCD
			AND t1.CCS_TEKIYOYMD = t2.SCSM_TEKIYOYMD
			AND t1.CCS_LCATCD = t2.SCSM_LCATCD
			AND t1.CCS_MCATCD = t2.SCSM_MCATCD
			AND t1.CCS_SCATCD = t2.SCSM_SCATCD;

  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_TEKIYOYMD, CCS_LCATCD, CCS_MCATCD, CCS_SCATCD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_2
				WHERE CCS_KCD_2 IS NULL
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_LCATCD, t1.CCS_MCATCD, t1.CCS_SCATCD, t1.CCS_TEKIYOYMD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CCS_IMPORTFILE, LEN(t1.CCS_IMPORTFILE) - PATINDEX('%|%', t1.CCS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CCS_KCD = t2.SSHM_KCD
			AND t1.CCS_TENCD = t2.SSHM_HTCD
			AND t1.CCS_SCD = t2.SSHM_SCD
			AND t1.CCS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CCS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t1 AS (
				SELECT *
				FROM APP_CATSHN_MST_now
				WHERE SCSM_DELFG <> 1
			)
		SELECT t1.*
		INTO #wt_IMPORT_CATSHOHIN_3
		FROM t1
		INNER JOIN #wt_IMPORT_CATSHOHIN_2 t2
		ON t1.SCSM_KCD = t2.CCS_KCD
			AND t1.SCSM_HTCD = t2.CCS_TENCD
			AND t1.SCSM_SCD = t2.CCS_SCD
			AND t1.SCSM_TEKIYOYMD = t2.CCS_TEKIYOYMD
			AND t1.SCSM_LCATCD = t2.CCS_LCATCD
			AND t1.SCSM_MCATCD = t2.CCS_MCATCD
			AND t1.SCSM_SCATCD = t2.CCS_SCATCD;

  -- 削除対象レコードの [削除フラグ] を設定
		UPDATE #wt_IMPORT_CATSHOHIN_3
		SET
			SCSM_DELFG = 1,
			SCSM_KOSINYMD = @NowDt,
			SCSM_KOSINTANTO = @Tanto;
			
  -- ＤＢレコードを更新
		INSERT INTO APP_CATSHN_MST_now
		SELECT *
		FROM #wt_IMPORT_CATSHOHIN_3;
		
-- [会社コード、店舗コード、商品コード] で予約削除（※ [適用日] 以降）
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_TEKIYOYMD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_1
				WHERE CCS_YDELKBN = 2
			),
			t2 AS (
				SELECT SCSM_KCD, SCSM_HTCD, SCSM_SCD, SCSM_TEKIYOYMD
				FROM APP_CATSHN_MST_now
				WHERE SCSM_DELFG <> 1
			),
			t3 AS (
				SELECT DISTINCT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_TEKIYOYMD
				FROM t1
				INNER JOIN t2
				ON t1.CCS_KCD = t2.SCSM_KCD
					AND t1.CCS_TENCD = t2.SCSM_HTCD
					AND t1.CCS_SCD = t2.SCSM_SCD
					AND t1.CCS_TEKIYOYMD <= t2.SCSM_TEKIYOYMD
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_TEKIYOYMD, t1.CCS_IMPORTFILE, t3.CCS_KCD AS CCS_KCD_2
		INTO #wt_IMPORT_CATSHOHIN_4
		FROM t1
		LEFT OUTER JOIN t3
		ON t1.CCS_KCD = t3.CCS_KCD
			AND t1.CCS_TENCD = t3.CCS_TENCD
			AND t1.CCS_SCD = t3.CCS_SCD
			AND t1.CCS_TEKIYOYMD = t3.CCS_TEKIYOYMD;
			
  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_TEKIYOYMD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_4
				WHERE CCS_KCD_2 IS NULL
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_TEKIYOYMD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CCS_IMPORTFILE, LEN(t1.CCS_IMPORTFILE) - PATINDEX('%|%', t1.CCS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CCS_KCD = t2.SSHM_KCD
			AND t1.CCS_TENCD = t2.SSHM_HTCD
			AND t1.CCS_SCD = t2.SSHM_SCD
			AND t1.CCS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CCS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t1 AS (
				SELECT *
				FROM APP_CATSHN_MST_now
				WHERE SCSM_DELFG <> 1
			),
			t2 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, MIN(CCS_TEKIYOYMD) AS CCS_TEKIYOYMD
				FROM #wt_IMPORT_CATSHOHIN_4
				WHERE CCS_KCD_2 IS NOT NULL
				GROUP BY CCS_KCD, CCS_TENCD, CCS_SCD
			)
		SELECT t1.*
		INTO #wt_IMPORT_CATSHOHIN_5
		FROM t1
		INNER JOIN t2
		ON t1.SCSM_KCD = t2.CCS_KCD
			AND t1.SCSM_HTCD = t2.CCS_TENCD
			AND t1.SCSM_SCD = t2.CCS_SCD
			AND t1.SCSM_TEKIYOYMD >= t2.CCS_TEKIYOYMD;
			
  -- 削除対象レコードの [削除フラグ] を設定
		UPDATE #wt_IMPORT_CATSHOHIN_5
		SET
			SCSM_DELFG = 1,
			SCSM_KOSINYMD = @NowDt,
			SCSM_KOSINTANTO = @Tanto;
			
  -- ＤＢレコードを更新
		INSERT INTO APP_CATSHN_MST_now
		SELECT *
		FROM #wt_IMPORT_CATSHOHIN_5;

-- [会社コード、店舗コード、商品コード、大カテゴリコード、中カテゴリコード、小カテゴリコード] でマスタ削除（※ [適用日] 時点）
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_LCATCD, CCS_MCATCD, CCS_SCATCD, CCS_TEKIYOYMD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_1
				WHERE CCS_MDELKBN = 1
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_LCATCD, t1.CCS_MCATCD, t1.CCS_SCATCD, t1.CCS_TEKIYOYMD, t1.CCS_IMPORTFILE, t2.SCSM_TEKIYOYMD
		INTO #wt_IMPORT_CATSHOHIN_101
		FROM t1
		LEFT OUTER JOIN vi_APP_CATSHN_MST t2
		ON t1.CCS_KCD = t2.SCSM_KCD
			AND t1.CCS_TENCD = t2.SCSM_HTCD
			AND t1.CCS_SCD = t2.SCSM_SCD
			AND t1.CCS_LCATCD = t2.SCSM_LCATCD
			AND t1.CCS_MCATCD = t2.SCSM_MCATCD
			AND t1.CCS_SCATCD = t2.SCSM_SCATCD
			AND t1.CCS_TEKIYOYMD >= t2.SCSM_TEKIYOYMD
			AND t1.CCS_TEKIYOYMD <= t2.SCSM_TEKIYOYMD_END;

  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_LCATCD, CCS_MCATCD, CCS_SCATCD, CCS_TEKIYOYMD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_101
				WHERE SCSM_TEKIYOYMD IS NULL
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_LCATCD, t1.CCS_MCATCD, t1.CCS_SCATCD, t1.CCS_TEKIYOYMD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CCS_IMPORTFILE, LEN(t1.CCS_IMPORTFILE) - PATINDEX('%|%', t1.CCS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CCS_KCD = t2.SSHM_KCD
			AND t1.CCS_TENCD = t2.SSHM_HTCD
			AND t1.CCS_SCD = t2.SSHM_SCD
			AND t1.CCS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CCS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t1 AS (
				SELECT *
				FROM APP_CATSHN_MST_now
				WHERE SCSM_DELFG = 0
			)
		SELECT t1.*, t2.CCS_TEKIYOYMD
		INTO #wt_IMPORT_CATSHOHIN_102
		FROM t1
		INNER JOIN #wt_IMPORT_CATSHOHIN_101 t2
		ON t1.SCSM_KCD = t2.CCS_KCD
			AND t1.SCSM_HTCD = t2.CCS_TENCD
			AND t1.SCSM_SCD = t2.CCS_SCD
			AND t1.SCSM_LCATCD = t2.CCS_LCATCD
			AND t1.SCSM_MCATCD = t2.CCS_MCATCD
			AND t1.SCSM_SCATCD = t2.CCS_SCATCD
			AND t1.SCSM_TEKIYOYMD = t2.SCSM_TEKIYOYMD;

  -- 削除対象レコードを編集
		UPDATE #wt_IMPORT_CATSHOHIN_102
		SET
			SCSM_TEKIYOYMD = CCS_TEKIYOYMD,
			SCSM_UPDATECNT = 0,
			SCSM_DELFG = 2,
			SCSM_INYMD = @NowDt,
			SCSM_INTANTO = @Tanto,
			SCSM_KOSINYMD = @NowDt,
			SCSM_KOSINTANTO = @Tanto
		WHERE SCSM_TEKIYOYMD < CCS_TEKIYOYMD;

		UPDATE #wt_IMPORT_CATSHOHIN_102
		SET
			SCSM_DELFG = 2,
			SCSM_KOSINYMD = @NowDt,
			SCSM_KOSINTANTO = @Tanto
		WHERE SCSM_TEKIYOYMD = CCS_TEKIYOYMD;
			
  -- ＤＢレコードを更新
		INSERT INTO APP_CATSHN_MST_now
		SELECT SCSM_KCD,
			SCSM_HTCD,
			SCSM_LCATCD,
			SCSM_MCATCD,
			SCSM_SCATCD,
			SCSM_SCD,
			SCSM_TEKIYOYMD,
			SCSM_UPDATECNT,
			SCSM_CATSBT,
			SCSM_APPKEISAIJYUN,
			SCSM_YDELKBN,
			SCSM_MDELKBN,
			SCSM_YOBI1,
			SCSM_YOBI2,
			SCSM_YOBI3,
			SCSM_YOBI4,
			SCSM_YOBI5,
			SCSM_YOBI6,
			SCSM_YOBI7,
			SCSM_YOBI8,
			SCSM_YOBI9,
			SCSM_IMPORTYMD,
			SCSM_IMPORTFILE,
			SCSM_DELFG,
			SCSM_INYMD,
			SCSM_INTANTO,
			SCSM_KOSINYMD,
			SCSM_KOSINTANTO
		FROM #wt_IMPORT_CATSHOHIN_102;

-- [会社コード、店舗コード、商品コード] でマスタ削除（※ [適用日] 時点）
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_TEKIYOYMD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_1
				WHERE CCS_MDELKBN = 2
			),
			t2 AS (
				SELECT DISTINCT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_TEKIYOYMD
				FROM t1
				INNER JOIN vi_APP_CATSHN_MST t2
				ON t1.CCS_KCD = t2.SCSM_KCD
					AND t1.CCS_TENCD = t2.SCSM_HTCD
					AND t1.CCS_SCD = t2.SCSM_SCD
					AND t1.CCS_TEKIYOYMD >= t2.SCSM_TEKIYOYMD
					AND t1.CCS_TEKIYOYMD <= t2.SCSM_TEKIYOYMD_END
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_TEKIYOYMD, t1.CCS_IMPORTFILE, t2.CCS_KCD AS CCS_KCD_2
		INTO #wt_IMPORT_CATSHOHIN_103
		FROM t1
		LEFT OUTER JOIN t2
		ON t1.CCS_KCD = t2.CCS_KCD
			AND t1.CCS_TENCD = t2.CCS_TENCD
			AND t1.CCS_SCD = t2.CCS_SCD
			AND t1.CCS_TEKIYOYMD = t2.CCS_TEKIYOYMD;

  -- 削除対象レコードが存在しない削除設定を取得
		WITH
			t1 AS (
				SELECT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_TEKIYOYMD, CCS_IMPORTFILE
				FROM #wt_IMPORT_CATSHOHIN_103
				WHERE CCS_KCD_2 IS NULL
			)
		SELECT t1.CCS_KCD, t1.CCS_TENCD, t1.CCS_SCD, t1.CCS_TEKIYOYMD,
			ISNULL(t2.SSHM_SHONAME, '') AS SSHM_SHONAME, RIGHT(t1.CCS_IMPORTFILE, LEN(t1.CCS_IMPORTFILE) - PATINDEX('%|%', t1.CCS_IMPORTFILE)) AS CSV_LINENO
		FROM t1
		LEFT OUTER JOIN vi_SHOHIN_MST t2
		ON t1.CCS_KCD = t2.SSHM_KCD
			AND t1.CCS_TENCD = t2.SSHM_HTCD
			AND t1.CCS_SCD = t2.SSHM_SCD
			AND t1.CCS_TEKIYOYMD >= t2.SSHM_TEKIYOYMD
			AND t1.CCS_TEKIYOYMD <= t2.SSHM_TEKIYOYMD_END;
		
  -- 削除対象レコードを取得
		WITH
			t2 AS (
				SELECT DISTINCT CCS_KCD, CCS_TENCD, CCS_SCD, CCS_TEKIYOYMD
				FROM #wt_IMPORT_CATSHOHIN_103
			)
		SELECT t1.*, t2.CCS_TEKIYOYMD
		INTO #wt_IMPORT_CATSHOHIN_104
		FROM vi_APP_CATSHN_MST t1
		INNER JOIN t2
		ON t1.SCSM_KCD = t2.CCS_KCD
			AND t1.SCSM_HTCD = t2.CCS_TENCD
			AND t1.SCSM_SCD = t2.CCS_SCD
			AND t1.SCSM_TEKIYOYMD <= t2.CCS_TEKIYOYMD
			AND t1.SCSM_TEKIYOYMD_END >= t2.CCS_TEKIYOYMD;

  -- 削除対象レコードを編集
		UPDATE #wt_IMPORT_CATSHOHIN_104
		SET
			SCSM_TEKIYOYMD = CCS_TEKIYOYMD,
			SCSM_UPDATECNT = 0,
			SCSM_DELFG = 2,
			SCSM_INYMD = @NowDt,
			SCSM_INTANTO = @Tanto,
			SCSM_KOSINYMD = @NowDt,
			SCSM_KOSINTANTO = @Tanto
		WHERE SCSM_TEKIYOYMD < CCS_TEKIYOYMD;

		UPDATE #wt_IMPORT_CATSHOHIN_104
		SET
			SCSM_DELFG = 2,
			SCSM_KOSINYMD = @NowDt,
			SCSM_KOSINTANTO = @Tanto
		WHERE SCSM_TEKIYOYMD = CCS_TEKIYOYMD;
			
  -- ＤＢレコードを更新
		INSERT INTO APP_CATSHN_MST_now
		SELECT SCSM_KCD,
			SCSM_HTCD,
			SCSM_LCATCD,
			SCSM_MCATCD,
			SCSM_SCATCD,
			SCSM_SCD,
			SCSM_TEKIYOYMD,
			SCSM_UPDATECNT,
			SCSM_CATSBT,
			SCSM_APPKEISAIJYUN,
			SCSM_YDELKBN,
			SCSM_MDELKBN,
			SCSM_YOBI1,
			SCSM_YOBI2,
			SCSM_YOBI3,
			SCSM_YOBI4,
			SCSM_YOBI5,
			SCSM_YOBI6,
			SCSM_YOBI7,
			SCSM_YOBI8,
			SCSM_YOBI9,
			SCSM_IMPORTYMD,
			SCSM_IMPORTFILE,
			SCSM_DELFG,
			SCSM_INYMD,
			SCSM_INTANTO,
			SCSM_KOSINYMD,
			SCSM_KOSINTANTO
		FROM #wt_IMPORT_CATSHOHIN_104;

-- レコード登録
		SELECT t1.*, t2.*
		INTO #wt_IMPORT_CATSHOHIN_6
		FROM #wt_IMPORT_CATSHOHIN_1 t1
		LEFT OUTER JOIN APP_CATSHN_MST_now t2
		ON t1.CCS_KCD = t2.SCSM_KCD
			AND t1.CCS_TENCD = t2.SCSM_HTCD
			AND t1.CCS_SCD = t2.SCSM_SCD
			AND t1.CCS_TEKIYOYMD = t2.SCSM_TEKIYOYMD
			AND t1.CCS_LCATCD = t2.SCSM_LCATCD
			AND t1.CCS_MCATCD = t2.SCSM_MCATCD
			AND t1.CCS_SCATCD = t2.SCSM_SCATCD;

  -- レコード更新
    -- 予約・マスタ 削除レコード
		INSERT INTO APP_CATSHN_MST_now
		SELECT
			SCSM_KCD,
			SCSM_HTCD,
			SCSM_LCATCD,
			SCSM_MCATCD,
			SCSM_SCATCD,
			SCSM_SCD,
			SCSM_TEKIYOYMD,
			SCSM_UPDATECNT,
			SCSM_CATSBT,
			SCSM_APPKEISAIJYUN,
			CCS_YDELKBN,
			CCS_MDELKBN,
			SCSM_YOBI1,
			SCSM_YOBI2,
			SCSM_YOBI3,
			SCSM_YOBI4,
			SCSM_YOBI5,
			SCSM_YOBI6,
			SCSM_YOBI7,
			SCSM_YOBI8,
			SCSM_YOBI9,
			CCS_IMPORTYMD,
			CCS_IMPORTFILE,
			SCSM_DELFG,
			SCSM_INYMD,
			SCSM_INTANTO,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_CATSHOHIN_6
		WHERE SCSM_KCD IS NOT NULL
			AND CCS_YDELKBN + CCS_MDELKBN > 0;
			
    -- 通常レコード
		INSERT INTO APP_CATSHN_MST_now
		SELECT
			SCSM_KCD,
			SCSM_HTCD,
			SCSM_LCATCD,
			SCSM_MCATCD,
			SCSM_SCATCD,
			SCSM_SCD,
			SCSM_TEKIYOYMD,
			SCSM_UPDATECNT,
			CCS_CATSBT,
			CCS_APPKEISAIJYUN,
			CCS_YDELKBN,
			CCS_MDELKBN,
			CCS_YOBI1,
			CCS_YOBI2,
			CCS_YOBI3,
			CCS_YOBI4,
			CCS_YOBI5,
			CCS_YOBI6,
			CCS_YOBI7,
			CCS_YOBI8,
			CCS_YOBI9,
			CCS_IMPORTYMD,
			CCS_IMPORTFILE,
			0,
			SCSM_INYMD,
			SCSM_INTANTO,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_CATSHOHIN_6
		WHERE SCSM_KCD IS NOT NULL
			AND CCS_YDELKBN = 0 AND CCS_MDELKBN = 0;

  -- レコード追加
    -- 予約・マスタ 削除レコード
		INSERT INTO APP_CATSHN_MST_now
		SELECT
			CCS_KCD,
			CCS_TENCD,
			CCS_LCATCD,
			CCS_MCATCD,
			CCS_SCATCD,
			CCS_SCD,
			CCS_TEKIYOYMD,
			0,
			CCS_CATSBT,
			CCS_APPKEISAIJYUN,
			CCS_YDELKBN,
			CCS_MDELKBN,
			CCS_YOBI1,
			CCS_YOBI2,
			CCS_YOBI3,
			CCS_YOBI4,
			CCS_YOBI5,
			CCS_YOBI6,
			CCS_YOBI7,
			CCS_YOBI8,
			CCS_YOBI9,
			CCS_IMPORTYMD,
			CCS_IMPORTFILE,
			1,
			@NowDt,
			@Tanto,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_CATSHOHIN_6
		WHERE SCSM_KCD IS NULL
			AND CCS_YDELKBN + CCS_MDELKBN > 0;

    -- 通常レコード
		INSERT INTO APP_CATSHN_MST_now
		SELECT
			CCS_KCD,
			CCS_TENCD,
			CCS_LCATCD,
			CCS_MCATCD,
			CCS_SCATCD,
			CCS_SCD,
			CCS_TEKIYOYMD,
			0,
			CCS_CATSBT,
			CCS_APPKEISAIJYUN,
			CCS_YDELKBN,
			CCS_MDELKBN,
			CCS_YOBI1,
			CCS_YOBI2,
			CCS_YOBI3,
			CCS_YOBI4,
			CCS_YOBI5,
			CCS_YOBI6,
			CCS_YOBI7,
			CCS_YOBI8,
			CCS_YOBI9,
			CCS_IMPORTYMD,
			CCS_IMPORTFILE,
			0,
			@NowDt,
			@Tanto,
			@NowDt,
			@Tanto
		FROM #wt_IMPORT_CATSHOHIN_6
		WHERE SCSM_KCD IS NULL
			AND CCS_YDELKBN = 0 AND CCS_MDELKBN = 0;

		IF @TranCnt = 0
            COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @TranCnt = 0  
            ROLLBACK TRANSACTION;
		ELSE IF XACT_STATE() <> -1
			ROLLBACK TRANSACTION svpt_IMPORT_CATSHOHIN_1;

		SET @ErrMessage = ERROR_MESSAGE();
        SET @ErrSeverity = ERROR_SEVERITY();
        SET @ErrState = ERROR_STATE();
  
        RAISERROR (@ErrMessage, @ErrSeverity, @ErrState );
	END CATCH
END
GO
