USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SETTING_MST]') AND type in (N'U'))
DROP TABLE [dbo].[SETTING_MST]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SETTING_MST](
	[SSTM_KCD] [int] NOT NULL,
	[SSTM_SETKBN] [varchar](50) NOT NULL,
	[SSTM_SETDTLKBN] [varchar](50) NOT NULL,
	[SSTM_SETVALUE_VC] [varchar](1000) NULL,
	[SSTM_SETVALUE_INT] [int] NULL,
	[SSTM_SETVALUE_DC] [decimal](18, 0) NULL,
	[SSTM_SETVALUE_DT] [datetime] NULL,
	[SSTM_NAME] [varchar](1000) NULL,
	[SSTM_DTLNAME] [varchar](1000) NULL,
	[SSTM_SETUMEI] [varchar](1000) NULL,
	[SSTM_INYMD] [datetime] NULL,
	[SSTM_KOSINYMD] [datetime] NULL,
 CONSTRAINT [PK_SETTING_MST] PRIMARY KEY CLUSTERED 
(
	[SSTM_KCD] ASC,
	[SSTM_SETKBN] ASC,
	[SSTM_SETDTLKBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO SETTING_MST
SELECT *
FROM #{-INISET_DB-}#.dbo.SETTING_MST;

DECLARE @dt datetime = GETDATE();

UPDATE SETTING_MST
SET SSTM_INYMD = @dt,
	SSTM_KOSINYMD = @dt;

GO
