USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INMIKEI_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[INMIKEI_TBL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INMIKEI_TBL](
	[SIMT_INMIKEIFLG] [tinyint] NOT NULL,
	[SIMT_INMIKEINAME] [varchar](20) NULL,
 CONSTRAINT [PK_INMIKEI_TBL] PRIMARY KEY CLUSTERED 
(
	[SIMT_INMIKEIFLG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO INMIKEI_TBL
SELECT *
FROM #{-INISET_DB-}#.dbo.INMIKEI_TBL;

GO
