USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BUMON_MST]') AND type in (N'U'))
DROP TABLE [dbo].[BUMON_MST]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUMON_MST](
	[SBMM_KCD] [int] NOT NULL,
	[SBMM_HTCD] [smallint] NOT NULL,
	[SBMM_BUMONCD] [smallint] NOT NULL,
	[SBMM_BUMONNAME] [varchar](20) NULL,
	[SBMM_KUKURICD] [tinyint] NULL,
	[SBMM_URIZEIKBN] [tinyint] NULL,
	[SBMM_SIIREZEIKBN] [tinyint] NULL,
	[SBMM_ZEIRITUKBN] [tinyint] NULL,
	[SBMM_PICKTANTO] [tinyint] NULL,
	[SBMM_SYUSYUTANTO] [tinyint] NULL,
	[SBMM_SHOHINTANTO] [tinyint] NULL,
	[SBMM_GENKARITU] [float] NULL,
	[SBMM_FSHAKBN] [tinyint] NULL,
	[SBMM_NOKEIFLG] [tinyint] NULL,
	[SBMM_CONTROLFLG] [tinyint] NULL,
	[SBMM_KOSINYMD] [datetime] NULL,
	[SBMM_KOSINTIME] [datetime] NULL,
	[SBMM_KOSINTANTO] [int] NULL,
 CONSTRAINT [PK_BUMON_MST] PRIMARY KEY CLUSTERED 
(
	[SBMM_KCD] ASC,
	[SBMM_HTCD] ASC,
	[SBMM_BUMONCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
