USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[R020_APP_ORDER_TRN]') AND type in (N'U'))
DROP TABLE [dbo].[R020_APP_ORDER_TRN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R020_APP_ORDER_TRN](
	[AOR_GPCD] [int] NOT NULL,
	[AOR_SCD] [bigint] NOT NULL,
	[AOR_APPKEISAIJYUN] [int] NOT NULL,
 CONSTRAINT [PK_R020_APP_ORDER_TRN] PRIMARY KEY CLUSTERED 
(
	[AOR_GPCD] ASC,
	[AOR_SCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
