USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZEIKBN_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[ZEIKBN_TBL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZEIKBN_TBL](
	[SZKT_ZEIKBN] [tinyint] NOT NULL,
	[SZKT_ZEIKBNNAME] [varchar](20) NOT NULL,
 CONSTRAINT [PK_ZEIKBN_TBL] PRIMARY KEY CLUSTERED 
(
	[SZKT_ZEIKBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO ZEIKBN_TBL
SELECT *
FROM #{-INISET_DB-}#.dbo.ZEIKBN_TBL;

GO
