USE [#{-BASE_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[YOUKIS_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[YOUKIS_TBL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[YOUKIS_TBL](
	[SYKT_YOUKIKBN] [tinyint] NOT NULL,
	[SYKT_YOUKINAME] [varchar](10) NULL,
 CONSTRAINT [PK_YOUKIS_TBL] PRIMARY KEY CLUSTERED 
(
	[SYKT_YOUKIKBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO YOUKIS_TBL
SELECT *
FROM #{-INISET_DB-}#.dbo.YOUKIS_TBL;

GO
