USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APP_CATSHN_M_now]') AND type in (N'U'))
DROP TABLE [dbo].[APP_CATSHN_M_now]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_CATSHN_M_now](
	[ACSM_HTCD] [int] NOT NULL,
	[ACSM_LCATCD] [char](4) NOT NULL,
	[ACSM_MCATCD] [char](4) NOT NULL,
	[ACSM_SCATCD] [char](4) NOT NULL,
	[ACSM_SCD] [bigint] NOT NULL,
	[ACSM_TEKIYOYMD] [datetime] NOT NULL,
	[ACSM_UPDATECNT] [int] NOT NULL,
	[ACSM_APPKEISAIJYUN] [int] NOT NULL,
	[ACSM_DELFG] [tinyint] NOT NULL,
	[ACSM_INYMD] [datetime] NOT NULL,
	[ACSM_INTANTO] [varchar](100) NOT NULL,
	[ACSM_KOSINYMD] [datetime] NOT NULL,
	[ACSM_KOSINTANTO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_APP_CATSHN_M_now] PRIMARY KEY CLUSTERED 
(
	[ACSM_HTCD] ASC,
	[ACSM_LCATCD] ASC,
	[ACSM_MCATCD] ASC,
	[ACSM_SCATCD] ASC,
	[ACSM_SCD] ASC,
	[ACSM_TEKIYOYMD] ASC,
	[ACSM_UPDATECNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
