USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_APP_CATSHN_M]') AND type in (N'V'))
DROP VIEW [dbo].[vi_APP_CATSHN_M]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_APP_CATSHN_M]
AS
SELECT d.*, ISNULL(e.ACSM_TEKIYOYMD_END, CAST('9999/12/31 23:59:59' AS datetime)) AS ACSM_TEKIYOYMD_END
FROM (
	SELECT *
	FROM APP_CATSHN_M_now
	WHERE ACSM_DELFG = 0) d
LEFT OUTER JOIN (
	SELECT c.ACSM_HTCD, c.ACSM_LCATCD, c.ACSM_MCATCD, c.ACSM_SCATCD, c.ACSM_SCD, c.ACSM_TEKIYOYMD, DATEADD(second, -1, MIN(c.ACSM_TEKIYOYMD_END)) AS ACSM_TEKIYOYMD_END
	FROM (
		SELECT a.ACSM_HTCD, a.ACSM_LCATCD, a.ACSM_MCATCD, a.ACSM_SCATCD, a.ACSM_SCD, a.ACSM_TEKIYOYMD, b.ACSM_TEKIYOYMD AS ACSM_TEKIYOYMD_END
		FROM (
			SELECT *
			FROM APP_CATSHN_M_now
			WHERE ACSM_DELFG <> 1) a
		INNER JOIN (
			SELECT *
			FROM APP_CATSHN_M_now
			WHERE ACSM_DELFG <> 1) b
		ON a.ACSM_HTCD = b.ACSM_HTCD
			AND a.ACSM_LCATCD = b.ACSM_LCATCD
			AND a.ACSM_MCATCD = b.ACSM_MCATCD
			AND a.ACSM_SCATCD = b.ACSM_SCATCD
			AND a.ACSM_SCD = b.ACSM_SCD
			AND a.ACSM_TEKIYOYMD < b.ACSM_TEKIYOYMD) c
	GROUP BY c.ACSM_HTCD, c.ACSM_LCATCD, c.ACSM_MCATCD, c.ACSM_SCATCD, c.ACSM_SCD, c.ACSM_TEKIYOYMD) e
ON d.ACSM_HTCD = e.ACSM_HTCD
	AND d.ACSM_LCATCD = e.ACSM_LCATCD
	AND d.ACSM_MCATCD = e.ACSM_MCATCD
	AND d.ACSM_SCATCD = e.ACSM_SCATCD
	AND d.ACSM_SCD = e.ACSM_SCD
	AND d.ACSM_TEKIYOYMD = e.ACSM_TEKIYOYMD

GO
