USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APP_CATSHN_M]') AND type in (N'U'))
DROP TABLE [dbo].[APP_CATSHN_M]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_CATSHN_M](
	[ACSM_HTCD] [int] NOT NULL,
	[ACSM_LCATCD] [char](4) NOT NULL,
	[ACSM_MCATCD] [char](4) NOT NULL,
	[ACSM_SCATCD] [char](4) NOT NULL,
	[ACSM_SCD] [bigint] NOT NULL,
	[ACSM_APPKEISAIJYUN] [int] NOT NULL,
	[ACSM_INSDAT] [datetime] NOT NULL,
	[ACSM_UPDAT] [datetime] NOT NULL,
	[ACSM_AUTOADDFLG] [tinyint] NOT NULL,
 CONSTRAINT [PK_APP_CATSHN_M] PRIMARY KEY CLUSTERED 
(
	[ACSM_HTCD] ASC,
	[ACSM_LCATCD] ASC,
	[ACSM_MCATCD] ASC,
	[ACSM_SCATCD] ASC,
	[ACSM_SCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APP_CATSHN_M] ADD  CONSTRAINT [DF_APP_CATSHN_M_ACSM_AUTOADDFLG]  DEFAULT ((0)) FOR [ACSM_AUTOADDFLG]
GO
