USE [#{-APP_DB-}#]
GO

DROP INDEX IF EXISTS [nci_APP_CATSHN_M_now_ACSM_DELFG_1] ON [dbo].[APP_CATSHN_M_now]
GO

CREATE NONCLUSTERED INDEX [nci_APP_CATSHN_M_now_ACSM_DELFG_1] ON [dbo].[APP_CATSHN_M_now]
(
	[ACSM_DELFG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
