USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KAKAKU_M]') AND type in (N'U'))
DROP TABLE [dbo].[KAKAKU_M]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KAKAKU_M](
	[KAK_HTCD] [int] NOT NULL,
	[KAK_SCD] [bigint] NOT NULL,
	[KAK_KIKAKUCD] [bigint] NOT NULL,
	[KAK_TOKUKBN] [int] NOT NULL,
	[KAK_TOKUSTR] [datetime] NOT NULL,
	[KAK_TOKUEND] [datetime] NOT NULL,
	[KAK_TOKUGENKA] [float] NOT NULL,
	[KAK_TOKUTANKA] [int] NOT NULL,
	[KAK_TSURYOSEIGEN] [smallint] NOT NULL,
	[KAK_TOKUKEISAIJUN] [int] NOT NULL,
	[KAK_TOKUSJKBN] [int] NOT NULL,
	[KAK_INYMD] [datetime] NOT NULL,
	[KAK_KOSINYMD] [datetime] NOT NULL,
	[KAK_KOSINTIME] [datetime] NOT NULL,
	[KAK_100BAIKA] [int] NULL,
	[KAK_KEISAI_OVERRIDE] [int] NULL,
 CONSTRAINT [PK_KAKAKU_M] PRIMARY KEY CLUSTERED 
(
	[KAK_HTCD] ASC,
	[KAK_SCD] ASC,
	[KAK_KIKAKUCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
