USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_KAKAKU_M]') AND type in (N'V'))
DROP VIEW [dbo].[vi_KAKAKU_M]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_KAKAKU_M]
AS
SELECT d.*, ISNULL(e.KAK_TEKIYOYMD_END, CAST('9999/12/31 23:59:59' AS datetime)) AS KAK_TEKIYOYMD_END
FROM (
	SELECT *
	FROM KAKAKU_M_now
	WHERE KAK_DELFG = 0) d
LEFT OUTER JOIN (
	SELECT c.KAK_HTCD, c.KAK_SCD, c.KAK_KIKAKUCD, c.KAK_TEKIYOYMD, DATEADD(second, -1, MIN(c.KAK_TEKIYOYMD_END)) AS KAK_TEKIYOYMD_END
	FROM (
		SELECT a.KAK_HTCD, a.KAK_SCD, a.KAK_KIKAKUCD, a.KAK_TEKIYOYMD, b.KAK_TEKIYOYMD AS KAK_TEKIYOYMD_END
		FROM (
			SELECT *
			FROM KAKAKU_M_now
			WHERE KAK_DELFG <> 1) a
		INNER JOIN (
			SELECT *
			FROM KAKAKU_M_now
			WHERE KAK_DELFG <> 1) b
		ON a.KAK_HTCD = b.KAK_HTCD
			AND a.KAK_SCD = b.KAK_SCD
			AND a.KAK_KIKAKUCD = b.KAK_KIKAKUCD
			AND a.KAK_TEKIYOYMD < b.KAK_TEKIYOYMD) c
	GROUP BY c.KAK_HTCD, c.KAK_SCD, c.KAK_KIKAKUCD, c.KAK_TEKIYOYMD) e
ON d.KAK_HTCD = e.KAK_HTCD
	AND d.KAK_SCD = e.KAK_SCD
	AND d.KAK_KIKAKUCD = e.KAK_KIKAKUCD
	AND d.KAK_TEKIYOYMD = e.KAK_TEKIYOYMD

GO
