USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MIXMATCH_M_now]') AND type in (N'U'))
DROP TABLE [dbo].[MIXMATCH_M_now]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MIXMATCH_M_now](
	[MIM_HTCD] [int] NOT NULL,
	[MIM_MMNO] [int] NOT NULL,
	[MIM_SCD] [bigint] NOT NULL,
	[MIM_TEKIYOYMD] [datetime] NOT NULL,
	[MIM_UPDATECNT] [int] NOT NULL,
	[MIM_DELFG] [tinyint] NOT NULL,
	[MIM_INYMD] [datetime] NOT NULL,
	[MIM_INTANTO] [varchar](100) NOT NULL,
	[MIM_KOSINYMD] [datetime] NOT NULL,
	[MIM_KOSINTANTO] [varchar](100) NOT NULL,
 CONSTRAINT [PK_MIXMATCH_M_now] PRIMARY KEY CLUSTERED 
(
	[MIM_HTCD] ASC,
	[MIM_MMNO] ASC,
	[MIM_SCD] ASC,
	[MIM_TEKIYOYMD] ASC,
	[MIM_UPDATECNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
