USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MIXMATCH_MST_now]') AND type in (N'V'))
DROP VIEW [dbo].[MIXMATCH_MST_now]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[MIXMATCH_MST_now]
AS
	SELECT a.*
	FROM #{-BASE_DB-}#.dbo.MIXMATCH_MST_now a
	INNER JOIN #{-BASE_DB-}#.dbo.MIXMATCH_MMNO b
	ON a.SMIM_MMNOBIG = b.CSVMMNO
GO
