USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[vi_MIXMATCHGRP_M]') AND type in (N'V'))
DROP VIEW [dbo].[vi_MIXMATCHGRP_M]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vi_MIXMATCHGRP_M]
AS
SELECT d.*, ISNULL(e.MGM_TEKIYOYMD_END, CAST('9999/12/31 23:59:59' AS datetime)) AS MGM_TEKIYOYMD_END
FROM (
	SELECT *
	FROM MIXMATCHGRP_M_now
	WHERE MGM_DELFG = 0) d
LEFT OUTER JOIN (
	SELECT c.MGM_HTCD, c.MGM_MMNO, c.MGM_TEKIYOYMD, DATEADD(second, -1, MIN(c.MGM_TEKIYOYMD_END)) AS MGM_TEKIYOYMD_END
	FROM (
		SELECT a.MGM_HTCD, a.MGM_MMNO, a.MGM_TEKIYOYMD, b.MGM_TEKIYOYMD AS MGM_TEKIYOYMD_END
		FROM (
			SELECT *
			FROM MIXMATCHGRP_M_now
			WHERE MGM_DELFG <> 1) a
		INNER JOIN (
			SELECT *
			FROM MIXMATCHGRP_M_now
			WHERE MGM_DELFG <> 1) b
		ON a.MGM_HTCD = b.MGM_HTCD
			AND a.MGM_MMNO = b.MGM_MMNO
			AND a.MGM_TEKIYOYMD < b.MGM_TEKIYOYMD) c
	GROUP BY c.MGM_HTCD, c.MGM_MMNO, c.MGM_TEKIYOYMD) e
ON d.MGM_HTCD = e.MGM_HTCD
	AND d.MGM_MMNO = e.MGM_MMNO
	AND d.MGM_TEKIYOYMD = e.MGM_TEKIYOYMD

GO
