USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APP_SETTING_M]') AND type in (N'U'))
DROP TABLE [dbo].[APP_SETTING_M]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_SETTING_M](
	[ASTM_SETKBN] [varchar](50) NOT NULL,
	[ASTM_SETDTLKBN] [varchar](50) NOT NULL,
	[ASTM_SETVALUE] [varchar](256) NOT NULL,
	[ASTM_APPDLKBN] [tinyint] NOT NULL,
	[ASTM_NAME] [varchar](256) NOT NULL,
	[ASTM_SETUMEI] [varchar](256) NULL,
	[ASTM_INSDAT] [datetime] NOT NULL,
	[ASTM_UPDAT] [datetime] NOT NULL,
 CONSTRAINT [PK_APP_SETTING_M] PRIMARY KEY CLUSTERED 
(
	[ASTM_SETKBN] ASC,
	[ASTM_SETDTLKBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO APP_SETTING_M
SELECT *
FROM #{-INISET_DB-}#.dbo.APP_SETTING_M;

UPDATE APP_SETTING_M
SET ASTM_SETVALUE = '#{-CalendarTekiCnt-}#'
WHERE ASTM_SETKBN = 'CalendarTekiyoCount' AND ASTM_SETDTLKBN = 'X';

UPDATE APP_SETTING_M
SET ASTM_SETVALUE = '#{-DbOperatingEnv-}#'
WHERE ASTM_SETKBN = 'DatabaseOperatingEnvironment' AND ASTM_SETDTLKBN = 'X';

DECLARE @dt datetime = GETDATE();

UPDATE APP_SETTING_M
SET ASTM_INSDAT = @dt,
	ASTM_UPDAT = @dt;

GO
