USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CATSHN_INSERT_SETTING]') AND type in (N'U'))
DROP TABLE [dbo].[CATSHN_INSERT_SETTING]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATSHN_INSERT_SETTING](
	[SJKBN] [tinyint] NOT NULL,
	[LCAT] [char](4) NOT NULL,
	[MCAT] [char](4) NOT NULL,
	[BUMON] [char](4) NOT NULL,
	[MEMO] [varchar](200) NULL,
 CONSTRAINT [PK_CATSHN_INSERT_SETTING] PRIMARY KEY CLUSTERED 
(
	[SJKBN] ASC,
	[LCAT] ASC,
	[MCAT] ASC,
	[BUMON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
