USE [#{-APP_DB-}#]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONVERT_FAVBTNFLG]') AND type in (N'FN'))
DROP FUNCTION [dbo].[CONVERT_FAVBTNFLG]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[CONVERT_FAVBTNFLG]
(
	@paramFavBtnFlg	tinyint
)
RETURNS tinyint
AS
BEGIN

	DECLARE @FAVBTNFLG tinyint

	IF @paramFavBtnFlg = 0
		BEGIN
			SET @FAVBTNFLG = 1
		END
	ELSE 
		BEGIN
			SET @FAVBTNFLG = 0
		END

	RETURN @FAVBTNFLG

END
GO
